### ISSUE TITLE
请问潘多拉怎么使用？

### ISSUE THREAD

**Issue by peqing** [maxlicheng/luci-app-unblockmusic#1]
恩山hiboy的固件https://www.right.com.cn/forum/thread-161324-1-1.html
怎么使用呢？

Padavan & N56U project community
Highcharts by Torstein Hønsi & Highsoft
Big icons designed by Freepik
Non-Commercial Use Only

**Comment by maxlicheng** [comment]
只支持OpenWRT/LEDE系统
