### ISSUE TITLE
可否编译一个v2.2.3 n1的版本吗？

### ISSUE THREAD

**Issue by liucan12138** [maxlicheng/luci-app-unblockmusic#100]
或者说newifid2可以通用吗？现在我使用的是openwrtmix，无法启动插件

**Comment by maxlicheng** [comment]
> 或者说newifid2可以通用吗？现在我使用的是openwrtmix，无法启动插件

已上传，qemu版本，兼容openwrtmix，[n1.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.3/n1.zip)
