### ISSUE TITLE
openwrt 无法启动

### ISSUE THREAD

**Issue by BROBIRD** [maxlicheng/luci-app-unblockmusic#12]
经测试发现似乎无法后台运行。

**Comment by BROBIRD** [comment]
建议运行命令改为
`nohup node /usr/share/unblockmusic/app.js -p $PORT &`

**Comment by maxlicheng** [comment]
lede 跟 openwrt是一致的吧，都可以正常运行才对。你是用这边编译好的ipk安装的还是自己编译的？要注意内核版本，版本不一样，即使安装了也不一定正常使用。还有能说明一下 nohup 运行命令的好处吗？我测试了一下，是可以正常运行的。在考虑是否加入到源码当中。

**Comment by BROBIRD** [comment]
编译的，源码是 coolsnowwolf/lede ，我这里无法启动

**Comment by BROBIRD** [comment]
暂时我也没法确定原因……我再观察观察

**Comment by alexyw** [comment]
用的Lean的LEDE，也不行，手工命令错误如下：
root@OpenWrt:~# node /usr/share/unblockmusic/app.js -p 5200
{ Error: getaddrinfo EAI_AGAIN
    at Object._errnoException (util.js:1022:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:104:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'interface3.music.163.com' }

**Comment by maxlicheng** [comment]
> 用的Lean的LEDE，也不行，手工命令错误如下：
> root@OpenWrt:~# node /usr/share/unblockmusic/app.js -p 5200
> { Error: getaddrinfo EAI_AGAIN
> at Object._errnoException (util.js:1022:11)
> at errnoException (dns.js:55:15)
> at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:104:26)
> code: 'EAI_AGAIN',
> errno: 'EAI_AGAIN',
> syscall: 'getaddrinfo',
> hostname: 'interface3.music.163.com' }

什么型号的路由器？插件是以什么方法安装的？

**Comment by alexyw** [comment]
> 
> 
> > 用的Lean的LEDE，也不行，手工命令错误如下：
> > root@OpenWrt:~# node /usr/share/unblockmusic/app.js -p 5200
> > { Error: getaddrinfo EAI_AGAIN
> > at Object._errnoException (util.js:1022:11)
> > at errnoException (dns.js:55:15)
> > at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:104:26)
> > code: 'EAI_AGAIN',
> > errno: 'EAI_AGAIN',
> > syscall: 'getaddrinfo',
> > hostname: 'interface3.music.163.com' }
> 
> 什么型号的路由器？插件是以什么方法安装的？

Hyper-V平台，使用coolsnowwolf的lede编译vhdx直接使用
可能是内核版本的问题，最新是4.9左右，没有4.14

**Comment by jliveusa** [comment]
node /usr/share/UnblockNeteaseMusic/app.js -p 5200
url.js:337
      this.hostname = toASCII(this.hostname, true);
                      ^

Error: Cannot convert name to ASCII
    at Url.parse (url.js:337:23)
    at urlParse (url.js:97:13)
    at request (/usr/share/UnblockNeteaseMusic/request.js:39:8)
    at httpdns (/usr/share/UnblockNeteaseMusic/app.js:70:45)
    at Object.<anonymous> (/usr/share/UnblockNeteaseMusic/app.js:72:14)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
官方openwrt，node版本8.16

**Comment by maxlicheng** [comment]
> node /usr/share/UnblockNeteaseMusic/app.js -p 5200
> url.js:337
> this.hostname = toASCII(this.hostname, true);
> ^
> 
> Error: Cannot convert name to ASCII
> at Url.parse (url.js:337:23)
> at urlParse (url.js:97:13)
> at request (/usr/share/UnblockNeteaseMusic/request.js:39:8)
> at httpdns (/usr/share/UnblockNeteaseMusic/app.js:70:45)
> at Object. (/usr/share/UnblockNeteaseMusic/app.js:72:14)
> at Module._compile (module.js:653:30)
> at Object.Module._extensions..js (module.js:664:10)
> at Module.load (module.js:566:32)
> at tryModuleLoad (module.js:506:12)
> at Function.Module._load (module.js:498:3)
> 官方openwrt，node版本8.16

什么路由器？
后台执行这条命令：ping music.163.com -c 1 | sed '1{s/[^(]*(//;s/).*//;q}'
看看能否获取到ip

**Comment by jliveusa** [comment]
N1，ping music.163.com -c 1 | sed '1{s/[^(](//;s/).//;q}'
PING music.163.com59.111.160.195 56 data bytes

**Comment by maxlicheng** [comment]
> N1，ping music.163.com -c 1 | sed '1{s/[^(](//;s/).//;q}'
> PING music.163.com59.111.160.195 56 data bytes

这是一个获取IP的命令，从结果里面可知，并没有正确获取到IP。
你打开/etc/init.d/路径下的unblockmusic文件，把40 至 44 行替换成以下内容
```
	if [ $TYPE = "default" ]; then
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -f $MUSIC_IP >/tmp/unblockmusic.log 2>&1 &
	else
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -f $MUSIC_IP -o $TYPE >/tmp/unblockmusic.log 2>&1 &
	fi
```

**Comment by maxlicheng** [comment]
> N1，ping music.163.com -c 1 | sed '1{s/[^(](//;s/).//;q}'
> PING music.163.com59.111.160.195 56 data bytes

发现语句被github格式化了，要用下面这条
```
ping music.163.com -c 1 | sed '1{s/[^(]*(//;s/).*//;q}'
```
不过无所谓了，你按上面的方式，把40至44行修改了就好。

**Comment by jliveusa** [comment]
尝试了，还是扑街了ORZ

**Comment by maxlicheng** [comment]
> 尝试了，还是扑街了ORZ

对了，你是自己编译的ipk还是安装github上传的ipk，建议两者都尝试一下。

**Comment by jliveusa** [comment]
不修改40-44行，ssh直接运行node /usr/share/UnblockNeteaseMusic/app.js -p 5200成功了，无论修改与否插件中开启就报错

**Comment by maxlicheng** [comment]
> 不修改40-44行，ssh直接运行node /usr/share/UnblockNeteaseMusic/app.js -p 5200成功了，无论修改与否插件中开启就报错

失能掉ipset再运行试试，有可能能是iptable重定向配置的引起的问题。

**Comment by maxlicheng** [comment]
新版本已经修复不能启动的问题，请各位升级v2.2.0版本

**Comment by RealKiro** [comment]
> 新版本已经修复不能启动的问题，请各位升级v2.2.0版本

仍然出错
![image](https://user-images.githubusercontent.com/33367701/62829919-ea7fa300-bc36-11e9-9864-ea80759d6fea.png)
![image](https://user-images.githubusercontent.com/33367701/62829922-f2d7de00-bc36-11e9-90c5-4cef61f60225.png)

**Comment by maxlicheng** [comment]
> > 新版本已经修复不能启动的问题，请各位升级v2.2.0版本
> 
> 仍然出错
> ![image](https://user-images.githubusercontent.com/33367701/62829919-ea7fa300-bc36-11e9-9864-ea80759d6fea.png)
> ![image](https://user-images.githubusercontent.com/33367701/62829922-f2d7de00-bc36-11e9-90c5-4cef61f60225.png)

/etc/config/unblockmusic 文件内容截图看看。
正常内容应为
```
	config unblockmusic
	option enabled '0'
	option musicapptype 'kuwo'
	option port '5200'
	option hport '5201'
```

**Comment by RealKiro** [comment]
> > > 新版本已经修复不能启动的问题，请各位升级v2.2.0版本
> > 
> > 
> > 仍然出错
> > ![image](https://user-images.githubusercontent.com/33367701/62829919-ea7fa300-bc36-11e9-9864-ea80759d6fea.png)
> > ![image](https://user-images.githubusercontent.com/33367701/62829922-f2d7de00-bc36-11e9-90c5-4cef61f60225.png)
> 
> /etc/config/unblockmusic 文件内容截图看看。
> 正常内容应为
> 
> ```
> config unblockmusic
> 	option enabled '0'
> 	option musicapptype 'kuwo'
> 	option port '5200'
> 	option hport '5201'
> ```
我是从Lean大屌的编译替换为你的插件后直接升级的，目前固件又换回去了，所以看不到了，只能等下个版本再尝试

**Comment by maxlicheng** [comment]
> 我是从Lean大屌的编译替换为你的插件后直接升级的，目前固件又换回去了，所以看不到了，只能等下个版本再尝试

lean的lede源码已经收录了本插件，不再需要另外克隆luci-app-unblockmusic源码。如果同时含有两个插件源码，确实有可能会因为配置文件不一致而启动不了。
