### ISSUE TITLE
希望能增加 ipv6支持

### ISSUE THREAD

**Issue by t66y100** [maxlicheng/luci-app-unblockmusic#125]
windows 10 ipv6，直接指定代理是可以用的，不设置就不行。
如果关闭ipv6，不设置代理也可以直接用。

忘记说了，我用的2.2.0，不知道最新版2.3.1是否已支持ipv6。

我用的是官方版openwrt 19.07.2，无法使用2.3.1.

最新版2.3.1的libopenssl似乎和官方Openwrt 19.07.2的版本不一致，我先装了transmission之类的软件，自动装了libopenssl， 但是版本号和libopenssl_1.1.1d-2_x86_64.ipk不同，libopenssl_1.1.1d-2_x86_64.ipk就装不上。直接跳过libopenssl_1.1.1d-2_x86_64.ipk的话，无法启动unblockmusic。

**Comment by hushanwei** [comment]
> 自己在防火墙里禁止发出到2407:ae80:200:1001::20，搞定了。

具体的命令是什么样的呢

**Comment by smilence86** [comment]
@t66y100 老哥怎么搞的，具体命令呢？
