### ISSUE TITLE
是否支持官方openwrt编译

### ISSUE THREAD

**Issue by zkzipoo** [maxlicheng/luci-app-unblockmusic#13]
试着编译官方固件 https://git.openwrt.org/openwrt/openwrt.git/

但是发现在luci application 里面找不到，是因为只支持lean大的编译环境吗

**Comment by maxlicheng** [comment]
把源码克隆到package目录下，在make menuconfig 中选中luci-app-unblockmusic即可。

**Comment by zkzipoo** [comment]
是这么操作的
![image](https://user-images.githubusercontent.com/3366892/61115230-ecb0df00-a489-11e9-9070-e71e901860c7.png)
但是在application下面没找到啊
![image](https://user-images.githubusercontent.com/3366892/61115396-444f4a80-a48a-11e9-85af-e00ef67b2655.png)
是不是我的编译的环境有问题，用的是windows 10自带的WSL，但是用ubuntu 19.01也不行，然后路由器的Soc是lantiq，这个不支持么

**Comment by maxlicheng** [comment]
什么路由器？要注意路由器主控是否支持FDU，不支持FDU则运行不了node.js，插件源码依赖于node.js。

**Comment by alexyw** [comment]
> 
> 
> 是这么操作的
> ![image](https://user-images.githubusercontent.com/3366892/61115230-ecb0df00-a489-11e9-9070-e71e901860c7.png)
> 但是在application下面没找到啊
> ![image](https://user-images.githubusercontent.com/3366892/61115396-444f4a80-a48a-11e9-85af-e00ef67b2655.png)
> 是不是我的编译的环境有问题，用的是windows 10自带的WSL，但是用ubuntu 19.01也不行，然后路由器的Soc是lantiq，这个不支持么

你要运行一下
./scripts/feeds update -a
./scripts/feeds install -a
再make menuconfig，就可以看到了

**Comment by zkzipoo** [comment]
> > 是这么操作的
> > ![image](https://user-images.githubusercontent.com/3366892/61115230-ecb0df00-a489-11e9-9070-e71e901860c7.png)
> > 但是在application下面没找到啊
> > ![image](https://user-images.githubusercontent.com/3366892/61115396-444f4a80-a48a-11e9-85af-e00ef67b2655.png)
> > 是不是我的编译的环境有问题，用的是windows 10自带的WSL，但是用ubuntu 19.01也不行，然后路由器的Soc是lantiq，这个不支持么
> 
> 你要运行一下
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> 再make menuconfig，就可以看到了

感谢回复，这个是做了的，而且我查了所有编好的module，里面并没有这个插件。

**Comment by zkzipoo** [comment]
> 什么路由器？要注意路由器主控是否支持FDU，不支持FDU则运行不了node.js，插件源码依赖于node.js。

路由器是这个 https://openwrt.org/toh/bt/homehub_v5a ,请问fdu是啥，这个我没查到，谢谢哈

**Comment by maxlicheng** [comment]
> > 什么路由器？要注意路由器主控是否支持FDU，不支持FDU则运行不了node.js，插件源码依赖于node.js。
> 
> 路由器是这个 https://openwrt.org/toh/bt/homehub_v5a ,请问fdu是啥，这个我没查到，谢谢哈

打错了，FPU 浮点数运算单元。
你可以查看make menuconfig，是否有node.js，并且需要选中node。
Languages  ---> 
Node.js  --->
-*- node.......... Node.js is a platform built on Chrome's JavaScript runtime 

可以选中则支持，不能选择则不支持。

**Comment by geol** [comment]
请问楼主问题解决了吗？我碰到一样的问题，lean大的源码可以选，官openwrt选不到。

**Comment by zkzipoo** [comment]
> 请问楼主问题解决了吗？我碰到一样的问题，lean大的源码可以选，官openwrt选不到。

没有，这个处理器可能不能对nodejs有很好的支持，MIPS这个架构还不是很友好啊[https://github.com/nodejs/node/pull/27992](url)

**Comment by MiChuancey** [comment]
遇到了同样的问题，应该不是CPU架构的问题。

**Comment by maxlicheng** [comment]
> 请问楼主问题解决了吗？我碰到一样的问题，lean大的源码可以选，官openwrt选不到。

插件依赖于node，进入make menuconfig查看，Langages ---> Node.js --->查看Node.js选项中是否有可选项，如无说明你的路由器不支持Node.js。若L大的源码支持，而官方不支持，请尝试更新node源码。
- 1.在feeds.conf.default文件中添加如下语句
```
 src-git node https://github.com/nxhack/openwrt-node-packages.git
```
-  2.添加完成后，依次执行以下命令
```
./scripts/feeds update node
rm ./package/feeds/packages/node
rm ./package/feeds/packages/node-*
./scripts/feeds install -a -p node
```
