### ISSUE TITLE
似乎会误伤别的网站

### ISSUE THREAD

**Issue by pupboss** [maxlicheng/luci-app-unblockmusic#143]
被误伤的域名是 static.tigerbbs.com，关闭unblockmusic之后就正常，或者关闭之后再立即打开也是正常，但是过一阵子就会劫持这个域名，使用自签名证书

我这里解析出来的IP是 `163.171.210.41`，会不会是某条规则误伤了163开头的IP，或者网易云的某个IP和其他公司的混用了

我来给一点自己的思路，这里面有没有什么定时任务，因为最开始的时候不会劫持这个域名，猜测是某个定时任务之后，导致新增了什么规则

**Comment by caliban511** [comment]
是不是DNS缓存的原因，导致误伤劫持会在一段时间后才生效？

**Comment by pupboss** [comment]
@caliban511 悬案解决了，看了他的源码，用的是 ipset 的方式，也就是说如果别的公司和云音乐共用同一个 CDN 或者服务器，就会被劫持
