### ISSUE TITLE
使用后网易云可以生效但微信小程序和公众号下方服务无法联网

### ISSUE THREAD

**Issue by kid-oh** [maxlicheng/luci-app-unblockmusic#17]
我的路由是华硕ac58u OpenWrt固件

**Comment by kid-oh** [comment]
换成手动代理就服务不了路由器了 密码对了也不行

**Comment by maxlicheng** [comment]
自动代理是最优的选择，手动代理会使手机所有流量都走代理，不可取，手动代理只适合用来下载歌曲，下载完毕后，要关掉手动代理。移动端的问题，跟系统和硬件差异性有关，大家反馈都不一样。选择最适合自己的吧。
