### ISSUE TITLE
openwrt x86-64安装ipk报错

### ISSUE THREAD

**Issue by thb007** [maxlicheng/luci-app-unblockmusic#18]
这是报错的代码
root@OpenWrt:/tmp/upload# opkg install luci-app-unblockmusic_1-36_all.ipk
Multiple packages (luci-app-unblockmusic and luci-app-unblockmusic) providing same name marked HOLD or PREFER. Using latest.
Installing luci-app-unblockmusic (1-36) to root...
Installing libstdcpp6 (7.4.0-1) to root...
Downloading https://openwrt.proxy.ustclug.org/snapshots/targets/x86/64/packages/libstdcpp6_7.4.0-1_x86_64.ipk
Collected errors:
 * check_data_file_clashes: Package libstdcpp6 wants to install file /usr/lib/libstdc++.so.6
        But that file is already provided by package  * libstdcpp
 * check_data_file_clashes: Package libstdcpp6 wants to install file /usr/lib/libstdc++.so.6.0.24
        But that file is already provided by package  * libstdcpp
 * check_data_file_clashes: Package libstdcpp6 wants to install file /usr/lib/libstdc++.so.6.0.24-gdb.py
        But that file is already provided by package  * libstdcpp
 * opkg_install_cmd: Cannot install package luci-app-unblockmusic.
root@OpenWrt:/tmp/upload#

**Comment by maxlicheng** [comment]
node.js安装了嘛？提示缺少库，你需要自行安装libstdcpp6_7.4.0-1_x86_64.ipk。

**Comment by thb007** [comment]
> node.js中安装了嘛？提示缺少库，你需要自行安装libstdcpp6_7.4.0-1_x86_64.ipk。

root@OpenWrt:/tmp/upload# opkg install node_v8.10.0-3_x86_64.ipk
Installing node (v8.10.0-3) to root...
Multiple packages (libstdcpp and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
Configuring node.
root@OpenWrt:/tmp/upload# opkg install luci-app-unblockmusic_1-36_all.ipk
Multiple packages (luci-app-unblockmusic and luci-app-unblockmusic) providing same name marked HOLD or PREFER. Using latest.
Installing luci-app-unblockmusic (1-36) to root...
Configuring luci-app-unblockmusic.
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Parse error (invalid command) at line 1, byte 0
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
uci: Entry not found
root@OpenWrt:/tmp/upload#

**Comment by maxlicheng** [comment]
> > node.js中安装了嘛？提示缺少库，你需要自行安装libstdcpp6_7.4.0-1_x86_64.ipk。
> 
> root@OpenWrt:/tmp/upload# opkg install node_v8.10.0-3_x86_64.ipk
> Installing node (v8.10.0-3) to root...
> Multiple packages (libstdcpp and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
> Configuring node.
> root@OpenWrt:/tmp/upload# opkg install luci-app-unblockmusic_1-36_all.ipk
> Multiple packages (luci-app-unblockmusic and luci-app-unblockmusic) providing same name marked HOLD or PREFER. Using latest.
> Installing luci-app-unblockmusic (1-36) to root...
> Configuring luci-app-unblockmusic.
> uci: Entry not found
> uci: Entry not found
> uci: Entry not found
> uci: Parse error (invalid command) at line 1, byte 0
> uci: Entry not found
> uci: Entry not found
> uci: Entry not found
> uci: Entry not found
> uci: Entry not found
> root@OpenWrt:/tmp/upload#

第一次见，什么版本的openwrt？建议自行编译ipk插件，不同版本的OP源码，安装会有异常。

**Comment by 1715173329** [comment]
> > > node.js中安装了嘛？提示缺少库，你需要自行安装libstdcpp6_7.4.0-1_x86_64.ipk。
> > 
> > 
> > root@OpenWrt:/tmp/upload# opkg install node_v8.10.0-3_x86_64.ipk
> > Installing node (v8.10.0-3) to root...
> > Multiple packages (libstdcpp and libstdcpp6) providing same name marked HOLD or PREFER. Using latest.
> > Configuring node.
> > root@OpenWrt:/tmp/upload# opkg install luci-app-unblockmusic_1-36_all.ipk
> > Multiple packages (luci-app-unblockmusic and luci-app-unblockmusic) providing same name marked HOLD or PREFER. Using latest.
> > Installing luci-app-unblockmusic (1-36) to root...
> > Configuring luci-app-unblockmusic.
> > uci: Entry not found
> > uci: Entry not found
> > uci: Entry not found
> > uci: Parse error (invalid command) at line 1, byte 0
> > uci: Entry not found
> > uci: Entry not found
> > uci: Entry not found
> > uci: Entry not found
> > uci: Entry not found
> > root@OpenWrt:/tmp/upload#
> 
> 第一次见，什么版本的openwrt？建议自行编译ipk插件，不同版本的OP源码，安装会有异常。

这是正常现象。。。
