### ISSUE TITLE
合并参考

### ISSUE THREAD

**Issue by RealKiro** [maxlicheng/luci-app-unblockmusic#19]
[基于你的Luci插件进行二改，使源项目代码更方便的在路由器上运行](https://github.com/project-openwrt/luci-app-unblockmusic)

**Comment by maxlicheng** [comment]
收到，感谢您的优化，很完美，我抽空处理一下。

**Comment by RealKiro** [comment]
> 收到，感谢您的优化，很完美，我抽空处理一下。

不是我做的，尚不确定有什么改动，也不确定是否能合并

**Comment by maxlicheng** [comment]
> > 收到，感谢您的优化，很完美，我抽空处理一下。
> 
> 不是我做的，尚不确定有什么改动，也不确定是否能合并

哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。

**Comment by RealKiro** [comment]
> > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > 
> > 
> > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> 
> 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。

经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常

**Comment by maxlicheng** [comment]
> > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > 
> > > 
> > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > 
> > 
> > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> 
> 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常

因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。

**Comment by 1715173329** [comment]
> > > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > > 
> > > > 
> > > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > > 
> > > 
> > > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> > 
> > 
> > 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常
> 
> 因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。

您好，请具体说明一下“断网”是什么情况。
目前本人亲测，开启ipset转发后仅会影响到网易云网页端无法正常访问（https://music.163.com），但并不会影响到整个网络正常运作；如关闭ipset转发，并不会产生问题。

**Comment by maxlicheng** [comment]
> > > > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > > > 
> > > > > 
> > > > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > > > 
> > > > 
> > > > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> > > 
> > > 
> > > 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常
> > 
> > 
> > 因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。
> 
> 您好，请具体说明一下“断网”是什么情况。
> 目前本人亲测，开启ipset转发后仅会导致无法正常访问[网易云音乐网页端](https://music.163.com)，但并不会干扰到整个网络的正常运作；如关闭ipset转发，并不会产生问题。
> 新版已解决开启IPSet后无法访问网页端的问题。

作者本人吗？很厉害啊，点赞。感谢您对插件的优化，不单解决了ipset转发问题，还把网页端的也修复了。之前安装体验了一下，会完全上不了网，应该其他插件配置冲突了，现在用干净的固件在测试，没有出现断网，效果很不错。我可以把你的代码合并过来嘛，只用部分功能，会注明来处。感谢。

**Comment by 1715173329** [comment]
> > > > > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > > > > 
> > > > > > 
> > > > > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > > > > 
> > > > > 
> > > > > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> > > > 
> > > > 
> > > > 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常
> > > 
> > > 
> > > 因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。
> > 
> > 
> > 您好，请具体说明一下“断网”是什么情况。
> > 目前本人亲测，开启ipset转发后仅会导致无法正常访问[网易云音乐网页端](https://music.163.com)，但并不会干扰到整个网络的正常运作；如关闭ipset转发，并不会产生问题。
> > 新版已解决开启IPSet后无法访问网页端的问题。
> 
> 作者本人吗？很厉害啊，点赞。感谢您对插件的优化，不单解决了ipset转发问题，还把网页端的也修复了。之前安装体验了一下，会完全上不了网，应该其他插件配置冲突了，现在用干净的固件在测试，没有出现断网，效果很不错。我可以把你的代码合并过来嘛，只用部分功能，会注明来处。感谢。

没事，在遵循GPLv3.0协议的情况下，您可以自由修改分发；
我个人的要求是，标注来源即可，其他的问题不大。

**Comment by maxlicheng** [comment]
> > > > > > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > > > > > 
> > > > > > > 
> > > > > > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > > > > > 
> > > > > > 
> > > > > > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> > > > > 
> > > > > 
> > > > > 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常
> > > > 
> > > > 
> > > > 因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。
> > > 
> > > 
> > > 您好，请具体说明一下“断网”是什么情况。
> > > 目前本人亲测，开启ipset转发后仅会导致无法正常访问[网易云音乐网页端](https://music.163.com)，但并不会干扰到整个网络的正常运作；如关闭ipset转发，并不会产生问题。
> > > 新版已解决开启IPSet后无法访问网页端的问题。
> > 
> > 
> > 作者本人吗？很厉害啊，点赞。感谢您对插件的优化，不单解决了ipset转发问题，还把网页端的也修复了。之前安装体验了一下，会完全上不了网，应该其他插件配置冲突了，现在用干净的固件在测试，没有出现断网，效果很不错。我可以把你的代码合并过来嘛，只用部分功能，会注明来处。感谢。
> 
> 没事，在遵循GPLv3.0协议的情况下，您可以自由修改分发；
> 我个人的要求是，标注来源即可，其他的问题不大。

好的，您的代码有很多值得学习的地方，再一次感谢。

**Comment by 1715173329** [comment]
> > > > > > > > > 收到，感谢您的优化，很完美，我抽空处理一下。
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不是我做的，尚不确定有什么改动，也不确定是否能合并
> > > > > > > 
> > > > > > > 
> > > > > > > 哦哦，好，我看看能不能联系到他本人。好的，我会提前验证一下。
> > > > > > 
> > > > > > 
> > > > > > 经测试体验，他二次修改的源码不需要手动代理就能点亮使用，安卓端旧版使用也正常
> > > > > 
> > > > > 
> > > > > 因为这个版本配置了防火墙参数，开启解锁会导致断网，体验不是很好，我再观察一下。
> > > > 
> > > > 
> > > > 您好，请具体说明一下“断网”是什么情况。
> > > > 目前本人亲测，开启ipset转发后仅会导致无法正常访问[网易云音乐网页端](https://music.163.com)，但并不会干扰到整个网络的正常运作；如关闭ipset转发，并不会产生问题。
> > > > 新版已解决开启IPSet后无法访问网页端的问题。
> > > 
> > > 
> > > 作者本人吗？很厉害啊，点赞。感谢您对插件的优化，不单解决了ipset转发问题，还把网页端的也修复了。之前安装体验了一下，会完全上不了网，应该其他插件配置冲突了，现在用干净的固件在测试，没有出现断网，效果很不错。我可以把你的代码合并过来嘛，只用部分功能，会注明来处。感谢。
> > 
> > 
> > 没事，在遵循GPLv3.0协议的情况下，您可以自由修改分发；
> > 我个人的要求是，标注来源即可，其他的问题不大。
> 
> 好的，您的代码有很多值得学习的地方，再一次感谢。

不客气 (
