### ISSUE TITLE
【2019.06.09】自编译L大新三固件    进英雄联盟地图就断线？

### ISSUE THREAD

**Issue by Godfavorstheinfantry** [maxlicheng/luci-app-unblockmusic#20]
![图片1](https://user-images.githubusercontent.com/21167262/62008052-700b4980-b187-11e9-99f6-6fb4c2ee336a.png)

**Comment by maxlicheng** [comment]
开了解锁网易云引起的嘛？停掉解锁正常吗？

**Comment by Godfavorstheinfantry** [comment]
应该和停掉也一样 T-T   可能是固件问题?

**Comment by maxlicheng** [comment]
> 停掉也一样 T-T 可能是固件问题?

插件有点多，有空你尽可能的停掉正在运行插件。自己不玩电脑端游戏，没办法测试。如果有结果希望反馈一下。

**Comment by Godfavorstheinfantry** [comment]
默认固件的状态好像没开启多少插件?  
百度有的说是mtu的问题但是我找不到这个设置在哪- -
有的说什么路由表放行- -  太高端了搞不懂- -
