### ISSUE TITLE
今天更新后在luci中有二条luci-app-unblockmusic选项，不知是为什么今天以前的版本不会

### ISSUE THREAD

**Issue by lllrrr** [maxlicheng/luci-app-unblockmusic#21]

**Comment by lllrrr** [comment]
是不是要将app目录改成luci-app-unblockmusic

**Comment by maxlicheng** [comment]
> 是不是要将app目录改成luci-app-unblockmusic

你是用L大的LEDE源码嘛？L大源码收录了本插件，需要把路径./package/lean/中luci-app-unblockmusic删掉，再进入make menuconfig中就只有一个插件了。

**Comment by lllrrr** [comment]
懂了，谢谢
