### ISSUE TITLE
在播放部分歌曲时默认音源给出的替换歌曲不是我所点的歌曲

### ISSUE THREAD

**Issue by XwbCHN** [maxlicheng/luci-app-unblockmusic#22]
周杰伦/amei-不该（周杰伦的床边故事）
我选择默认音源替换
在播放时却不是这首歌
会不会是插件的替换机制不完善
有没有可能修复这种少数情况呢

**Comment by maxlicheng** [comment]
切换其它音源试试


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: XwbCHN <notifications@github.com>
发送时间: 2019年8月2日 23:32
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[maxlicheng/luci-app-unblockmusic] 在播放部分歌曲时默认音源给出的替换歌曲不是我所点的歌曲 (#22)




周杰伦/amei-不该（周杰伦的床边故事）
 我选择默认音源替换
 在播放时却不是这首歌
 会不会是插件的替换机制不完善
 有没有可能修复这种少数情况呢

**Comment by maxlicheng** [comment]
> 周杰伦/amei-不该（周杰伦的床边故事）
> 我选择默认音源替换
> 在播放时却不是这首歌

酷我音源是正常的，核心功能作者也推荐用 酷我

**Comment by XwbCHN** [comment]
好的 希望下个版本能添加一个提示 这样可以方便他人 避免碰到我这样的情况 谢谢
