### ISSUE TITLE
安装后进不去路由器管理界面

### ISSUE THREAD

**Issue by chanho0** [maxlicheng/luci-app-unblockmusic#23]
错误提示
/usr/lib/lua/luci/dispatcher.lua:567: Invalid controller file found
The file '/usr/lib/lua/luci/controller/unblockmusic.lua' contains an invalid module line.
Please verify whether the module name is set to 'luci.controller.unblockmusic' - It must correspond to the file path!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:567: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:593: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:261: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by chanho0** [comment]
不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去

**Comment by maxlicheng** [comment]
> 不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去

没保存完成就调转其他页面了嘛？你把/tmp/路径下载的luci-indexcache删掉重启路由器试试。这个插件没有关系，是op系统的问题。

**Comment by chanho0** [comment]
> 
> 
> > 不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去
> 
> 没保存完成就调转其他页面了嘛？你把/tmp/路径下载的luci-indexcache删掉重启路由器试试。这个插件没有关系，是op系统的问题。

没有找到indexcache这个文件，我tmp里面所有的翻了，只能找到luci-modulecache，我直接删这个也没有用

**Comment by maxlicheng** [comment]
> > > 不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去
> > 
> > 
> > 没保存完成就调转其他页面了嘛？你把/tmp/路径下载的luci-indexcache删掉重启路由器试试。这个插件没有关系，是op系统的问题。
> 
> 没有找到indexcache这个文件，我tmp里面所有的翻了，只能找到luci-modulecache，我直接删这个也没有用

那就看看其他人有没有解决方法分享一下了。

**Comment by chanho0** [comment]
> 
> 
> > > > 不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去
> > > 
> > > 
> > > 没保存完成就调转其他页面了嘛？你把/tmp/路径下载的luci-indexcache删掉重启路由器试试。这个插件没有关系，是op系统的问题。
> > 
> > 
> > 没有找到indexcache这个文件，我tmp里面所有的翻了，只能找到luci-modulecache，我直接删这个也没有用
> 
> 那就看看其他人有没有解决方法分享一下了。

有没有什么办法恢复出厂设置，百度方法都是要复位键的

**Comment by maxlicheng** [comment]
> > > > > 不影响除网易云以外的其他功能，网能上，去广告也正常，但网易云和管理界面上不去
> > > > 
> > > > 
> > > > 没保存完成就调转其他页面了嘛？你把/tmp/路径下载的luci-indexcache删掉重启路由器试试。这个插件没有关系，是op系统的问题。
> > > 
> > > 
> > > 没有找到indexcache这个文件，我tmp里面所有的翻了，只能找到luci-modulecache，我直接删这个也没有用
> > 
> > 
> > 那就看看其他人有没有解决方法分享一下了。
> 
> 有没有什么办法恢复出厂设置，百度方法都是要复位键的

重刷固件就好了，也可以 用 系统->备份/升级->执行重置 进行重置

**Comment by 1715173329** [comment]
不用那么麻烦。。
ssh执行 `rm -rf /tmp/luci-*` 就完事

**Comment by coolsnowwolf** [comment]
死循环了，本地的 lookback proxy 没做处理

**Comment by coolsnowwolf** [comment]
现在的版本已解决

**Comment by superbeantop** [comment]
ssh 删除/usr/lib/lua/luci/controller/unblockmusic.lua 文件 亲测有效
