### ISSUE TITLE
koolshare lede 2.3.2开启就断网

### ISSUE THREAD

**Issue by xesygao** [maxlicheng/luci-app-unblockmusic#24]
准确的说是一安装luci-app-unblockmusic就断网，ipv4没网，ipv6正常

**Comment by maxlicheng** [comment]
打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
```
	if [ $TYPE = "default" ]; then
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
	else
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
	fi
```
还不成就只能去掉ipset，手动进行代理。

**Comment by xesygao** [comment]
> 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> 
> ```
> 	if [ $TYPE = "default" ]; then
> 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> 	else
> 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> 	fi
> ```
> 
> 还不成就只能去掉ipset，手动进行代理。

还是不行，只要安装，就算不运行程序也上不了网

**Comment by maxlicheng** [comment]
> > 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> > ```
> > 	if [ $TYPE = "default" ]; then
> > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> > 	else
> > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> > 	fi
> > ```
> > 
> > 
> > 还不成就只能去掉ipset，手动进行代理。
> 
> 还是不行，只要安装，就算不运行程序也上不了网

用新版本试试[x86_64-v2.2.0](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/x86_64-v2.2.0.zip)

**Comment by xesygao** [comment]
> > > 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> > > ```
> > > 	if [ $TYPE = "default" ]; then
> > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> > > 	else
> > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> > > 	fi
> > > ```
> > > 
> > > 
> > > 还不成就只能去掉ipset，手动进行代理。
> > 
> > 
> > 还是不行，只要安装，就算不运行程序也上不了网
> 
> 用新版本试试[x86_64-v2.2.0](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/x86_64-v2.2.0.zip)

感谢，晚上回去试试。nopenssl版本需要严格一致吗。我的是libopenssl1.1

**Comment by maxlicheng** [comment]
> > > > 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> > > > ```
> > > > 	if [ $TYPE = "default" ]; then
> > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> > > > 	else
> > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> > > > 	fi
> > > > ```
> > > > 
> > > > 
> > > > 还不成就只能去掉ipset，手动进行代理。
> > > 
> > > 
> > > 还是不行，只要安装，就算不运行程序也上不了网
> > 
> > 
> > 用新版本试试[x86_64-v2.2.0](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/x86_64-v2.2.0.zip)
> 
> 感谢，晚上回去试试。nopenssl版本需要严格一致吗。我的是libopenssl1.1

没要求，还是不行在安装高版本的试试。

**Comment by xesygao** [comment]
> > > > > 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> > > > > ```
> > > > > 	if [ $TYPE = "default" ]; then
> > > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> > > > > 	else
> > > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> > > > > 	fi
> > > > > ```
> > > > > 
> > > > > 
> > > > > 还不成就只能去掉ipset，手动进行代理。
> > > > 
> > > > 
> > > > 还是不行，只要安装，就算不运行程序也上不了网
> > > 
> > > 
> > > 用新版本试试[x86_64-v2.2.0](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/x86_64-v2.2.0.zip)
> > 
> > 
> > 感谢，晚上回去试试。nopenssl版本需要严格一致吗。我的是libopenssl1.1
> 
> 没要求，还是不行在安装高版本的试试。

感谢，可以使用了。还有个小问题问下，安卓最新版也需要设置代理才行吗？

**Comment by maxlicheng** [comment]
> > > > > > 打开/etc/init.d/目录下的unblockmusic文件，删除第10行，再将40至44行替换为以下内容。
> > > > > > ```
> > > > > > 	if [ $TYPE = "default" ]; then
> > > > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT >/tmp/unblockmusic.log 2>&1 &
> > > > > > 	else
> > > > > > 			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
> > > > > > 	fi
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > 还不成就只能去掉ipset，手动进行代理。
> > > > > 
> > > > > 
> > > > > 还是不行，只要安装，就算不运行程序也上不了网
> > > > 
> > > > 
> > > > 用新版本试试[x86_64-v2.2.0](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/x86_64-v2.2.0.zip)
> > > 
> > > 
> > > 感谢，晚上回去试试。nopenssl版本需要严格一致吗。我的是libopenssl1.1
> > 
> > 
> > 没要求，还是不行在安装高版本的试试。
> 
> 感谢，可以使用了。还有个小问题问下，安卓最新版也需要设置代理才行吗？

手上没有安卓的机器，群上说需要安装低版本的网易云，你研究一下。
