### ISSUE TITLE
UnblockNeteaseMusic部分为什么不直接同步更新

### ISSUE THREAD

**Issue by mjyhj** [maxlicheng/luci-app-unblockmusic#25]
还要指定17，18这个版本。
然后大雕那边收纳你这个，先是官方升到18，然后你再跟随升到18，再git pull给大雕？？

直接弄成实时同步最新的不好吗

**Comment by maxlicheng** [comment]
> 还要指定17，18这个版本。
> 然后大雕那边收纳你这个，先是官方升到18，然后你再跟随升到18，再git pull给大雕？？
> 
> 直接弄成实时同步最新的不好吗

插件编译都只能指定特定版本，目前还无法实现同步更新。
0.17.0跟0.18.0区别不大，不更也没问题，想要更新，单独编译UnblockNeteaseMusic ipk，单独安装就可以更新了。无需要再安装luci-app-unblockmusic ipk。
关于源码方面，已经咨询过Lean，同意并允许合并其修改后的源码，经过检验测试源码稳定性后，手动更新到本项目上，目前github项目上并没有相互关联。
嗯，会去找找，看看有没有更好的同步机制。

**Comment by mjyhj** [comment]
可以把本体不要编译进去，LUCI直接添加一栏，检测当前版本，随时下载替换，并且自定义保存路径。毕竟后期LUCI成熟了，基本不用再搞LUCI，这个东西他们一直在维护，时不时更新，自己手动点一下LUCI更新本体就好了

**Comment by maxlicheng** [comment]
> 可以把本体不要编译进去，LUCI直接添加一栏，检测当前版本，随时下载替换，并且自定义保存路径。毕竟后期LUCI成熟了，基本不用再搞LUCI，这个东西他们一直在维护，时不时更新，自己手动点一下LUCI更新本体就好了

嗯，你这个同步更新机制不错，我抽空研究一下。

**Comment by lllrrr** [comment]
恩山small的frp就是这样的，可以选版本升级

**Comment by lllrrr** [comment]
不对，不是small的，是这个帖子，有源码https://www.right.com.cn/forum/thread-306836-1-1.html
