### ISSUE TITLE
今天git pull后编译，新三，无法启动

### ISSUE THREAD

**Issue by lllrrr** [maxlicheng/luci-app-unblockmusic#26]
![20190807221739](https://user-images.githubusercontent.com/31834680/62630393-693bbe00-b961-11e9-8acd-ff92c3050de6.png)

**Comment by ihuaer** [comment]
同样的问题

**Comment by maxlicheng** [comment]
基于什么源编译的？你们试试我编译好的 [newifid2-v2.2.0.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/newifid2-v2.2.0.zip)

**Comment by zq758** [comment]
好像是/etc/config/unblockmusic的问题，用https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/config/unblockmusic这个文件替换了就没问题

**Comment by maxlicheng** [comment]
> 好像是/etc/config/unblockmusic的问题，用[https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/config/unblockmusic这个文件替换了就没问题](https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/config/unblockmusic%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E6%9B%BF%E6%8D%A2%E4%BA%86%E5%B0%B1%E6%B2%A1%E9%97%AE%E9%A2%98)

谢谢反馈，所以是git pull后的文件不完整的问题引起的？

**Comment by zq758** [comment]
应该是升级时没有替换配置文件

**Comment by maxlicheng** [comment]
> 应该是升级时没有替换配置文件

哦哦，那应该将插件卸载后，再进行安装。

**Comment by zq758** [comment]
新版插件对安卓网易云音乐（6.2.3）无效，提示无版权，uwp下有效，luci-app-unblockmusic和unlockmusic都重新卸载安装了。也可能不是新版插件问题，前昨天用pac代理就也是这样。

**Comment by maxlicheng** [comment]
> 新版插件对安卓网易云音乐（6.2.3）无效，提示无版权，uwp下有效，luci-app-unblockmusic和unlockmusic都重新卸载安装了。也可能不是新版插件问题，前昨天用pac代理就也是这样。

装回旧的v2.1.0 试试

**Comment by lllrrr** [comment]
> 
> 
> 基于什么源编译的？你们试试我编译好的 [newifid2-v2.2.0.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0/newifid2-v2.2.0.zip)
用的官方的18.06.4正式版源码，以前都是正常

**Comment by lllrrr** [comment]
> 
> 
> 好像是/etc/config/unblockmusic的问题，用[https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/config/unblockmusic这个文件替换了就没问题](https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/config/unblockmusic%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6%E6%9B%BF%E6%8D%A2%E4%BA%86%E5%B0%B1%E6%B2%A1%E9%97%AE%E9%A2%98)
可能是文件的权限问题，
