### ISSUE TITLE
刚编译的lean的openwrt无法启动

### ISSUE THREAD

**Issue by iwowcn** [maxlicheng/luci-app-unblockmusic#28]
版本分别是0.18.0和2.2.0
最新源码编译，无法启动，日志提示“Port must be a number higher than 0 and lower than 65535.
”

**Comment by maxlicheng** [comment]
是git clone方式下载的插件源码嘛？你查看一下路由器/etc/config/目录下的unblockmusic文件，截个图看看。然后你再对比一下源码下的这个文件，要跟源码一直。尽量卸载原来插件再安装新版本插件。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: iwowcn <notifications@github.com>
发送时间: 2019年8月9日 10:49
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[maxlicheng/luci-app-unblockmusic] 刚编译的lean的openwrt无法启动 (#28)




版本分别是0.18.0和2.2.0
最新源码编译，无法启动，日志提示“Port must be a number higher than 0 and lower than 65535.
”

**Comment by lllrrr** [comment]
今天试着换成https://github.com/project-openwrt/UnblockNeteaseMusic的编译固件后可以正常启动

**Comment by maxlicheng** [comment]
> 今天试着换成[https://github.com/project-openwrt/UnblockNeteaseMusic的编译固件后可以正常启动](https://github.com/project-openwrt/UnblockNeteaseMusic%E7%9A%84%E7%BC%96%E8%AF%91%E5%9B%BA%E4%BB%B6%E5%90%8E%E5%8F%AF%E4%BB%A5%E6%AD%A3%E5%B8%B8%E5%90%AF%E5%8A%A8)

那就好。
