### ISSUE TITLE
使用x86平台网易云，电脑端和IPAD 可以实现解锁功能，安卓手机苹果手机均无法解锁

### ISSUE THREAD

**Issue by tonygrooy** [maxlicheng/luci-app-unblockmusic#29]
使用x86平台网易云，电脑端和IPAD 可以实现解锁功能，安卓手机苹果手机均无法解锁

**Comment by tonygrooy** [comment]
openwrt

**Comment by maxlicheng** [comment]
> 使用x86平台网易云，电脑端和IPAD 可以实现解锁功能，安卓手机苹果手机均无法解锁

降级了嘛，ios和安卓。移动端的网易云都需要安装低版本，我的是iPhone，降级之后自动代理正常。

**Comment by maxlicheng** [comment]
- 截止至2019年9月13日，作者使用的网易云都是可以自动代理的。
- 以下是作者使用的各个系统的网易云音乐客户端版本，供大家参考。
- Win10：v2.5.3（Build:197601）
- IOS13：v5.8.0
- Android：v4.3.1.567509
- 以上就是作者使用的客户端版本，自动代理功能均正常。
