### ISSUE TITLE
macOS解锁需手动输入pac代理地址

### ISSUE THREAD

**Issue by heartofrainbow** [maxlicheng/luci-app-unblockmusic#30]
如题，最新版的插件确实可以解锁最新版macOS上的网易云的歌曲了，但是README中没说的是需要在勾选网络配置中的“自动配置代理”后，URL需要填写pac代理地址：

> http://192.168.1.1:5200/proxy.pac

如果路由器地址是192.168.1.1的话。
配置完后即可正常解锁。

**Comment by maxlicheng** [comment]
> 如题，最新版的插件确实可以解锁最新版macOS上的网易云的歌曲了，但是README中没说的是需要在勾选网络配置中的“自动配置代理”后，URL需要填写pac代理地址：
> 
> > http://192.168.1.1:5200/proxy.pac
> 
> 如果路由器地址是192.168.1.1的话。
> 配置完后即可正常解锁。

是的，我昨天抽空测试了一下黑苹果的网易云，其实只要勾选“自动发现代理”就可以了，不用填写url了，你试试。
![MacOS_views1](https://user-images.githubusercontent.com/40309661/62781402-864fc880-baea-11e9-8607-188847a369d3.jpg)

**Comment by heartofrainbow** [comment]
> > 如题，最新版的插件确实可以解锁最新版macOS上的网易云的歌曲了，但是README中没说的是需要在勾选网络配置中的“自动配置代理”后，URL需要填写pac代理地址：
> > > http://192.168.1.1:5200/proxy.pac
> > 
> > 
> > 如果路由器地址是192.168.1.1的话。
> > 配置完后即可正常解锁。
> 
> 是的，我昨天抽空测试了一下黑苹果的网易云，其实只要勾选“自动发现代理”就可以了，不用填写url了，你试试。
> ![MacOS_views1](https://user-images.githubusercontent.com/40309661/62781402-864fc880-baea-11e9-8607-188847a369d3.jpg)

我刚刚也尝试了一下，我这里不行，选择自动发现代理以后解锁失效，路由器那边日志也没有记录。我觉得可能是由于路由器上同时还运行了$$R代理的原因。。。。。。

**Comment by maxlicheng** [comment]
关闭ipv6试试

/etc/init.d/odhcpd disable
/etc/init.d/odhcpd stop
