### ISSUE TITLE
安卓版网易云音乐无法自动代理，已降级5.8.0

### ISSUE THREAD

**Issue by Liumik233** [maxlicheng/luci-app-unblockmusic#31]
安卓版网易云音乐无法自动代理，已降级5.8.0

**Comment by maxlicheng** [comment]
> 安卓版网易云音乐无法自动代理，已降级5.8.0

安卓要用网易云v4.3.1，需要填自动代理链接。
![android-views2](https://user-images.githubusercontent.com/40309661/62818303-5cdd7e00-bb78-11e9-8000-2b9934c193c6.jpg)
![android-views1](https://user-images.githubusercontent.com/40309661/62818307-649d2280-bb78-11e9-844e-e5438dcaa15a.jpg)

**Comment by Liumik233** [comment]
之前一直是用的自动代理，也没问题，但是最近突然就不管用了，而且Google play会提示无互联网连接

**Comment by EuropeanWithSSR** [comment]
我从酷安下载4.2.0.310743版本，并按上面设置后，歌曲依然是灰色的。
