### ISSUE TITLE
网易云官网打不开

### ISSUE THREAD

**Issue by muyuqiyan** [maxlicheng/luci-app-unblockmusic#32]
代理模式自动 版本2.2.0

**Comment by maxlicheng** [comment]
> 代理模式自动 版本2.2.0

我测试了一下，可以正常打开。

**Comment by muyuqiyan** [comment]
那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的    电脑上浏览器打不开music.163.com  手机浏览器显示：
连接可能不可信


为了保护你的隐私，Alook断开了到 music.163.com 的连接

警告: 这个网站的证书可能不安全

继续访问可能存在风险

**Comment by maxlicheng** [comment]
> 那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的 电脑上浏览器打不开music.163.com 手机浏览器显示：
> 连接可能不可信
> 
> 为了保护你的隐私，Alook断开了到 music.163.com 的连接
> 
> 警告: 这个网站的证书可能不安全
> 
> 继续访问可能存在风险

估计是插件正常运行时你就直接opkg升级了，正常应该停止正在运行的插件，然后再升级。

**Comment by maxlicheng** [comment]
> 那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的 电脑上浏览器打不开music.163.com 手机浏览器显示：
> 连接可能不可信
> 
> 为了保护你的隐私，Alook断开了到 music.163.com 的连接
> 
> 警告: 这个网站的证书可能不安全
> 
> 继续访问可能存在风险

建议你，卸载现有的v2.2.0插件，然后再安装v2.1.0插件，启用后，正在运行，再停用，然后卸载。完成这些步骤后，重新安装v2.2.0

**Comment by muyuqiyan** [comment]
> > 那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的 电脑上浏览器打不开music.163.com 手机浏览器显示：
> > 连接可能不可信
> > 为了保护你的隐私，Alook断开了到 music.163.com 的连接
> > 警告: 这个网站的证书可能不安全
> > 继续访问可能存在风险
> 
> 建议你，卸载现有的v2.2.0插件，然后再安装v2.1.0插件，启用后，正在运行，再停用，然后卸载。完成这些步骤后，重新安装v2.2.0

怎么卸载，或者怎么完全清除目录   removed不知道怎么卸载

**Comment by maxlicheng** [comment]
> > > 那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的 电脑上浏览器打不开music.163.com 手机浏览器显示：
> > > 连接可能不可信
> > > 为了保护你的隐私，Alook断开了到 music.163.com 的连接
> > > 警告: 这个网站的证书可能不安全
> > > 继续访问可能存在风险
> > 
> > 
> > 建议你，卸载现有的v2.2.0插件，然后再安装v2.1.0插件，启用后，正在运行，再停用，然后卸载。完成这些步骤后，重新安装v2.2.0
> 
> 怎么卸载，或者怎么完全清除目录 removed不知道怎么卸载
```
opkg removed luci-app-unblockmusic
opkg removde UnblockNeteaseMusic
```

**Comment by muyuqiyan** [comment]
> > > > 那可能是我路由器问题吧，系统版本koolshare2.32 解锁插件是手动升级的 电脑上浏览器打不开music.163.com 手机浏览器显示：
> > > > 连接可能不可信
> > > > 为了保护你的隐私，Alook断开了到 music.163.com 的连接
> > > > 警告: 这个网站的证书可能不安全
> > > > 继续访问可能存在风险
> > > 
> > > 
> > > 建议你，卸载现有的v2.2.0插件，然后再安装v2.1.0插件，启用后，正在运行，再停用，然后卸载。完成这些步骤后，重新安装v2.2.0
> > 
> > 
> > 怎么卸载，或者怎么完全清除目录 removed不知道怎么卸载
> 
> ```
> opkg removed luci-app-unblockmusic
> opkg removed UnblockNeteaseMusic
> ```

卸载不了，是在根目录运行 还是在其他目录运行

**Comment by nondanee** [comment]
@muyuqiyan 
CA 证书装过吗？
没装的话会警告不安全 (打不开)

**Comment by muyuqiyan** [comment]
> @muyuqiyan
> CA 证书装过吗？
> 没装的话会警告不安全 (打不开)
没装

**Comment by maxlicheng** [comment]
> @muyuqiyan
> CA 证书装过吗？
> 没装的话会警告不安全 (打不开)

谢谢大佬的关注，说明一下情况，因为路由器爱好者们不一定都是技术宅或者程序员，所以同同是linux内核的路由器需要用web界面来配置（如果都懂的话就不用插件了，后台直接运行命令就可以了）。嗯，就是面向的群体不一样，有了这个插件就可以通过脚本一键式运行您的项目，方便更多的人使用。证书方面这边都没有概念，我自己也还需要研究一下，再给大伙儿普及。

**Comment by nondanee** [comment]
@muyuqiyan 
https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
装了就能打开了

@maxlicheng 
好，有问题你答不上的话可以直接艾特我

**Comment by muyuqiyan** [comment]
证书安装了依旧打不开 ![批注 2019-08-14 203038.png](https://tupp.xyz/2019/08/14/15657859725d53ff74364a5.png)

**Comment by muyuqiyan** [comment]
> @muyuqiyan
> https://raw.githubusercontent.com/nondanee/UnblockNeteaseMusic/master/ca.crt
> 装了就能打开了
> 
> @maxlicheng
> 好，有问题你答不上的话可以直接艾特我
操作失误把问题关了好像  装了证书依旧打不开
![批注 2019-08-14 203038.png](https://tupp.xyz/2019/08/14/15657859725d53ff74364a5.png)

**Comment by nondanee** [comment]
@muyuqiyan 
不会吧，是不是插件挂掉了？
加 https 呢？

**Comment by muyuqiyan** [comment]
> @muyuqiyan
> 不会吧，是不是插件挂掉了？
> 加 https 呢？

同样打不开，旧版本没关闭升级的，luci页面里的开关有时会失效

**Comment by nondanee** [comment]
你之前的问题

> music.163.com 手机浏览器显示：
> 连接可能不可信
>
> 为了保护你的隐私，Alook断开了到 music.163.com 的连接
>
> 警告: 这个网站的证书可能不安全
>
> 继续访问可能存在风险

安装证书就能解决

现在这个问题，感觉是插件没在运行，你自己排查下

**Comment by muyuqiyan** [comment]
路由器系统搞其他的搞崩溃了，重装解决了
