### ISSUE TITLE
开启自动代理后Google play会提示未连接到互联网

### ISSUE THREAD

**Issue by 338317** [maxlicheng/luci-app-unblockmusic#33]
开启自动代理后Google play会提示未连接到互联网 
![Screenshot_20190812-121818](https://user-images.githubusercontent.com/50410851/62845594-d0f45f00-bcfb-11e9-9bdb-4e8b407d84b5.png)

**Comment by maxlicheng** [comment]
好，感谢您的反馈，我记录一下，有解决方式时再通知您。

**Comment by hushanwei** [comment]
+1，路由器用的是ssr代理

**Comment by maxlicheng** [comment]
@338317 @hushanwei 因为自己没有安卓机器，拿模拟器试了下，wifi填写自动代理链接后，Google Play可以正常使用。你们参考试试。
![自动代理1](https://user-images.githubusercontent.com/40309661/64105227-6ab5a600-cda8-11e9-91b5-93a079719df2.jpg)
![网易云歌曲截图1](https://user-images.githubusercontent.com/40309661/64105242-7012f080-cda8-11e9-8460-de761d7d19fb.jpg)
![google play](https://user-images.githubusercontent.com/40309661/64105279-802ad000-cda8-11e9-9829-d958c104be63.jpg)
