### ISSUE TITLE
mipsel_24kc和mipsel_1004kc_dsp

### ISSUE THREAD

**Issue by JSDT-YH** [maxlicheng/luci-app-unblockmusic#34]
插件依赖是mipsel_24kc的
但是我用的Intel大神的Pandorabox里边需求是mipsel_1004kc_dsp
请问大神，有办法转换下没有？

**Comment by maxlicheng** [comment]
> 插件依赖是mipsel_24kc的
> 但是我用的Intel大神的Pandorabox里边需求是mipsel_1004kc_dsp
> 请问大神，有办法转换下没有？

这个不叫依赖，这是路由器芯片架构，编译器根据路由器主控芯片架构自动编译生成的，只能自己编译。

**Comment by JSDT-YH** [comment]
我的也是新3，按说这机型一样，架构应该一样，可为什么Intel大神的Pandorabox和Openwrt的架构不一样呢？

**Comment by maxlicheng** [comment]
没玩过Pandorabox，自己拿Pandorabox源码编译个插件试试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JSDT-YH <notifications@github.com>
发送时间: 2019年8月17日 21:20
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com>
抄送: maxlicheng <1661695769@qq.com>, Comment <comment@noreply.github.com>
主题: 回复：[maxlicheng/luci-app-unblockmusic] mipsel_24kc和mipsel_1004kc_dsp (#34)




我的也是新3，按说这机型一样，架构应该一样，可为什么Intel大神的Pandorabox和Openwrt的架构不一样呢？

**Comment by JSDT-YH** [comment]
大白一个，学习学习  :-p
