### ISSUE TITLE
建议增加一些可配置项

### ISSUE THREAD

**Issue by xesygao** [maxlicheng/luci-app-unblockmusic#35]
例如
- 音源多选排序
- 严格模式(严格模式建议自动添加-e http://music.163.com)
- 端口自定义

**Comment by maxlicheng** [comment]
> 例如
> 
> * 音源多选排序
> * 严格模式(严格模式建议自动添加-e http://music.163.com)
> * 端口自定义

嗯，记下来了，后续逐步实现一下。

**Comment by maxlicheng** [comment]
> 例如
> 
> * 音源多选排序
> * 严格模式(严格模式建议自动添加-e http://music.163.com)
> * 端口自定义

多参数配置的可下载[[1715173329]](https://github.com/1715173329) [二次优化](https://github.com/project-openwrt/luci-app-unblockmusic)后的插件进行体验。
