### ISSUE TITLE
用户名密码问题

### ISSUE THREAD

**Issue by zhaoyi151205** [maxlicheng/luci-app-unblockmusic#36]
由于想把端口开放到公网上使用，但考虑安全问题，能否加上用户名密码？？

**Comment by maxlicheng** [comment]
> 由于想把端口开放到公网上使用，但考虑安全问题，能否加上用户名密码？？

你是路由器有公网嘛？还是说部署到VPS上面？
路由器插件是为了方便更多的人使用，简化了很多功能，进阶设置后续有计划做一个单独的选项卡。
如果是将项目部署到VPS上，可以参考核心功能：[nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)，有很多部署到云服务器上的方法和使用教程。

**Comment by zhaoyi151205** [comment]
> > 由于想把端口开放到公网上使用，但考虑安全问题，能否加上用户名密码？？
> 
> 你是路由器有公网嘛？还是说部署到VPS上面？
> 路由器插件是为了方便更多的人使用，简化了很多功能，进阶设置后续有计划做一个单独的选项卡。
> 如果是将项目部署到VPS上，可以参考核心功能：[nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)，有很多部署到云服务器上的方法和使用教程。

我是在路由器上的，路由器能否把用户名密码作为可选项，加到管理页面上去？（LEDE X86）
