### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by z1219176085** [maxlicheng/luci-app-unblockmusic#4]
[![QQ截图20190615184319.jpg](https://i.loli.net/2019/06/15/5d04cbdbe30a756850.jpg)](https://i.loli.net/2019/06/15/5d04cbdbe30a756850.jpg)

**Comment by maxlicheng** [comment]
插件并不需要aclocal-1.15这个依赖啊，你先别选中unblockmusic插件，看看整个路由器固件能否编译通过。

**Comment by z1219176085** [comment]
[![QQ截图20190615231733.jpg](https://i.loli.net/2019/06/15/5d050e638176663064.jpg)](https://i.loli.net/2019/06/15/5d050e638176663064.jpg)

**Comment by z1219176085** [comment]
[nk@localhost lede]$ make -j1 V=s  
make[1]: Entering directory `/home/nk/lede'
make[2]: Entering directory `/home/nk/lede'
+ mkdir -p /home/nk/lede/staging_dir/target-mips_24kc_musl
+ cd /home/nk/lede/staging_dir/target-mips_24kc_musl
+ mkdir -p bin lib include stamp
mkdir -p /home/nk/lede/build_dir/target-mips_24kc_musl/stamp
touch /home/nk/lede/staging_dir/target-mips_24kc_musl/.prepared
make[3]: Entering directory `/home/nk/lede/toolchain/gdb'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/home/nk/lede/toolchain/gdb'
time: toolchain/gdb/compile#0.00#0.00#0.15
make[3]: Entering directory `/home/nk/lede/toolchain/binutils'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/home/nk/lede/toolchain/binutils'
time: toolchain/binutils/compile#0.00#0.00#0.01
make[3]: Entering directory `/home/nk/lede/toolchain/gcc/initial'
make[3]: Nothing to be done for `compile'.
make[3]: Leaving directory `/home/nk/lede/toolchain/gcc/initial'
time: toolchain/gcc/initial/compile#0.00#0.00#0.06
make[3]: Entering directory `/home/nk/lede/toolchain/kernel-headers'
mkdir -p /home/nk/lede/dl
SHELL= flock /home/nk/lede/tmp/.linux-4.9.180.tar.xz.flock -c '  	/home/nk/lede/scripts/download.pl "/home/nk/lede/dl" "linux-4.9.180.tar.xz" "d25a490d62a3e96a587333e163862585eac4086fc8d4893b4ec1711e7d387c5f" "" "@KERNEL/linux/kernel/v4.x"    '
+ curl -f --connect-timeout 20 --retry 5 --location --insecure http://mirrors.ustc.edu.cn/kernel.org/linux/kernel/v4.x/linux-4.9.180.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Cannot create file /home/nk/lede/dl/linux-4.9.180.tar.xz.dl: Permission denied
sh: /home/nk/lede/dl/linux-4.9.180.tar.xz.hash: Permission denied
  0 89.1M    0  7300    0     0  38143      0  0:40:50 --:--:--  0:40:50 38219
curl: (23) Failed writing body (0 != 7300)
make[3]: *** [/home/nk/lede/dl/linux-4.9.180.tar.xz] Error 13
make[3]: Leaving directory `/home/nk/lede/toolchain/kernel-headers'
time: toolchain/kernel-headers/compile#0.03#0.04#0.62
make[2]: *** [toolchain/kernel-headers/compile] Error 2
make[2]: Leaving directory `/home/nk/lede'
make[1]: *** [/home/nk/lede/staging_dir/toolchain-mips_24kc_gcc-7.4.0_musl/stamp/.toolchain_compile] Error 2
make[1]: Leaving directory `/home/nk/lede'
make: *** [world] 错误 2

**Comment by z1219176085** [comment]
编译成功了

**Comment by maxlicheng** [comment]
node.js下载后放到dl目录，再编译试试。

**Comment by z1219176085** [comment]
一直在dl目录里

**Comment by z1219176085** [comment]
又试了一次[![QQ截图20190616001403.jpg](https://i.loli.net/2019/06/16/5d05196c73f2261228.jpg)](https://i.loli.net/2019/06/16/5d05196c73f2261228.jpg)

**Comment by maxlicheng** [comment]
应该是什么依赖没下载完整，你ssr开全局，节点选美国，执行make download V=s，完毕后再编译试试

**Comment by zxlhhyccc** [comment]
> 应该是什么依赖没下载完整，你ssr开全局，节点选美国，执行make download V=s，完毕后再编译试试

我在luci里找不到luci-app-unblockmusic，openwrt未识别：
![1%_LWAVJMY) 2YH(MF2}0L6](https://user-images.githubusercontent.com/45259624/59554207-0289cc00-8fd2-11e9-8df2-a2b7f40a23b2.png)

**Comment by maxlicheng** [comment]
luci-app-unblockmusic的路径你放哪了？pwd打印出来看看。

**Comment by zxlhhyccc** [comment]
> luci-app-unblockmusic的路径你放哪了？pwd打印出来看看。

![VW7DQTDH1S_JABJMVM6H3OA](https://user-images.githubusercontent.com/45259624/59554350-3e259580-8fd4-11e9-89ba-d12eecbec109.png)
我选择的型号是斐讯k3，是不是不支持？

**Comment by maxlicheng** [comment]
没那么严格啊，这个路径是没有问题的啊，路由器型号也没影响，你放到上一个路径看看make menuconfig 能不能识别到。

**Comment by zxlhhyccc** [comment]
> 没那么严格啊，这个路径是没有问题的啊，路由器型号也没影响，你放到上一个路径看看make menuconfig 能不能识别到。
放到上一级也无法识别，但我改为其他型号的路由，却能识别。。。。

**Comment by zxlhhyccc** [comment]
> 没那么严格啊，这个路径是没有问题的啊，路由器型号也没影响，你放到上一个路径看看make menuconfig 能不能识别到。

烦请大佬查查什么原因？或者修复一下呗！谢谢！

**Comment by maxlicheng** [comment]
刚查了， node.js 不支持k3，k3没有node.js，所以插件不显示。 这是官方OpenWRT源码的问题，想办法让k3的路由器型号支持node.js，插件就可以显示了。

**Comment by maxlicheng** [comment]
OpenWRT的 node.js 依赖于 HAS_FPU，而整个 Target System (Broadcom BCM47xx/53xx (ARM))  类别的 HAS_FPU都是关闭的，所以斐讯K3也同样不支持node.js，大家朝这个方向努力一下，看看能不能解决HAS_FPU依赖。

**Comment by zxlhhyccc** [comment]
> OpenWRT的 node.js 依赖于 HAS_FPU，而整个 Target System (Broadcom BCM47xx/53xx (ARM)) 类别的 HAS_FPU都是关闭的，所以斐讯K3也同样不支持node.js，大家朝这个方向努力一下，看看能不能解决HAS_FPU依赖。

有没有办法让HAS_FPU打开呢？

**Comment by maxlicheng** [comment]
研究过了，很多依赖，解决不了呢。你上恩山论坛开贴问问。

**Comment by z1219176085** [comment]
全局美国节点执行make download V=s，编译还是一样的错误

**Comment by maxlicheng** [comment]
> 全局美国节点执行make download V=s，编译还是一样的错误

什么路由器呢？

**Comment by z1219176085** [comment]
> > 全局美国节点执行make download V=s，编译还是一样的错误
> 
> 什么路由器呢？

wndr4300

**Comment by maxlicheng** [comment]
> > > 全局美国节点执行make download V=s，编译还是一样的错误
> > 
> > 
> > 什么路由器呢？
> 
> wndr4300

试了一下，这个型号，全编译是正常的，单独编译会报错。全编译后是有生成ipk的，已经放到releases了，下载安装试试。https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v1.1.0/wndr4300-luci-app-unblockmusic-ipk.zip

**Comment by z1219176085** [comment]
成功了，非常感谢
