### ISSUE TITLE
OPENWRT 18.06无法自动代理

### ISSUE THREAD

**Issue by admi-229133** [maxlicheng/luci-app-unblockmusic#40]
OPENWRT官方的源码 用你的源码发现无法自动代理 但是设置成手动代理就正常 不知道是哪个有问题

**Comment by admi-229133** [comment]
还有个问题就是 缓存会满 不会自动清理掉 之前用着用着缓存就满了 70多M都不够 然后路由后台都进不去了 直接卡死 然后重启路由才能用

**Comment by maxlicheng** [comment]
这个确实比较严重，下个版本会解决一下。关于不能自动代理的问题，设备差异性太大(路由器的差异，固件版本的差异，客户端设备的差异)，暂时无法定位。我的是Lean的LEDE源码编译的新三路由固件，ios13，网易云5.8.0，目前自动代理正常，除了最近几天有些歌曲显示不存在外，下载和播放都正常。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: admi-229133 <notifications@github.com&gt;
发送时间: 2019年8月28日 15:42
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] OPENWRT 18.06无法自动代理 (#40)




还有个问题就是 缓存会满 不会自动清理掉 之前用着用着缓存就满了 70多M都不够 然后路由后台都进不去了 直接卡死 然后重启路由才能用

**Comment by admi-229133** [comment]
啥时候更新修复啊？我PC端用的倒是没问题 但是我安卓手机设置手动代理 服务器主机设置的是路由IP 端口设置5200 对本地对象绕过localhost 然后去网易云音乐听周杰伦的歌 然后路由内存刷刷的掉 半小时后进都进不去路由了

**Comment by maxlicheng** [comment]
最近没有更新计划，你打开/etc/init.d/unblockmusic文件，把第69行屏蔽了(或者删掉)，这样插件就不会生成日志了。重新运行试试。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: admi-229133 <notifications@github.com&gt;
发送时间: 2019年8月30日 13:48
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] OPENWRT 18.06无法自动代理 (#40)




啥时候更新修复啊？我PC端用的倒是没问题 但是我安卓手机设置手动代理 服务器主机设置的是路由IP 端口设置5200 对本地对象绕过localhost 然后去网易云音乐听周杰伦的歌 然后路由内存刷刷的掉 半小时后进都进不去路由了

**Comment by thisdk** [comment]
感谢作者写出呢么好的插件,我也得openwrt18.06的源码..可以手动代理..自动代理不行.有没有什么办法可以先不更新就可以自动代理

**Comment by maxlicheng** [comment]
> 感谢作者写出呢么好的插件,我也得openwrt18.06的源码..可以手动代理..自动代理不行.有没有什么办法可以先不更新就可以自动代理

安装旧版本的网易云客户端试试
- win10：v2.5.3（Build:197601）
- ios：v5.8.0
- android：v4.3.1.567509
以上就是作者使用的客户端版本，自动代理功能正常。

**Comment by zzhang1987** [comment]
刚刚在OpenWrt 18.06上成功的用上了自动代理


感觉初始化代码里面
	$ipt_n -I PREROUTING -p tcp -m set --match-set music dst -j cloud_music
这个很容易出问题
我在路由器还有squid透明代理，把80端口指向了3128 。如果再加上这个规则就会导致网易云音乐完全无法访问。所以我吧这部发改成了
$ipn_n -A MyOtherChain -p tcp -m set --match-set music dst -j cloud_music
然后就work了。

**Comment by zzhang1987** [comment]
另外一个问题就是这个工具本质上是一种流量劫持，那么透明代理规则中的443部分是否有必要？https怎么实现流量劫持？

**Comment by zzhang1987** [comment]
> 
> 
> 另外一个问题就是这个工具本质上是一种流量劫持，那么透明代理规则中的443部分是否有必要？https怎么实现流量劫持？

 居然是用的sslbump，自己在签个CA导入之后就perfect了

**Comment by maxlicheng** [comment]
设备差异性较大，无法一一解决。建议更新编译最新源码安装尝试。
