### ISSUE TITLE
守护功能

### ISSUE THREAD

**Issue by twtjy2008** [maxlicheng/luci-app-unblockmusic#41]
非常感谢提供这么好的插件。请问有守护功能吗？如果没有，可否添加守护功能呢？

**Comment by maxlicheng** [comment]
想加，但普通路由器装不了那么大的插件。只有软路由可以，所以没有加了。
用node-forever插件。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: twtjy2008 <notifications@github.com&gt;
发送时间: 2019年8月29日 00:00
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 守护功能 (#41)




非常感谢提供这么好的插件。请问有守护功能吗？如果没有，可否添加守护功能呢？

**Comment by maxlicheng** [comment]
是的
```
forever start /usr/share/UnblockNeteaseMusic/app.js -p 5200
```
源码中的node要更新一下，你什么路由器？普通路由器更新node没有意义。

**Comment by twtjy2008** [comment]
用的是LEDE Koolshare，可以装forever的
