### ISSUE TITLE
get_latest_release

### ISSUE THREAD

**Issue by mjyhj** [maxlicheng/luci-app-unblockmusic#42]
curl -s https://github.com/nondanee/UnblockNeteaseMusic/releases| grep -oP "/releases/tag/[^\"^']+"| grep -oP "[^/^\"^']+"| head -n3|tail -n1

**Comment by maxlicheng** [comment]
好，了解，下个版本才用你这个方式。



发自我的iPhone


------------------ Original ------------------

**Comment by maxlicheng** [comment]
> curl -s [https://github.com/nondanee/UnblockNeteaseMusic/releases|](https://github.com/nondanee/UnblockNeteaseMusic/releases%7C) grep -oP "/releases/tag/[^"^']+"| grep -oP "[^/^"^']+"| head -n3|tail -n1

已经在尝试了，准备参考v2ray的更新方式。
```
curl -s https://api.github.com/repos/nondanee/UnblockNeteaseMusic/releases/latest
```
获取json格式，然后再去解析。
