### ISSUE TITLE
内存会满

### ISSUE THREAD

**Issue by admi-229133** [maxlicheng/luci-app-unblockmusic#43]
啥时候更新修复啊？ 但是我安卓手机设置手动代理 服务器主机设置的是路由IP 端口设置5200 对本地对象绕过localhost 然后去网易云音乐听周杰伦的歌 然后路由内存刷刷的掉 半小时后进都进不去路由了

_Originally posted by @admi-229133 in https://github.com/maxlicheng/luci-app-unblockmusic/issues/40#issuecomment-526465755_

**Comment by maxlicheng** [comment]
> 啥时候更新修复啊？ 但是我安卓手机设置手动代理 服务器主机设置的是路由IP 端口设置5200 对本地对象绕过localhost 然后去网易云音乐听周杰伦的歌 然后路由内存刷刷的掉 半小时后进都进不去路由了
> 
> _Originally posted by @admi-229133 in [#40 (comment)](https://github.com/maxlicheng/luci-app-unblockmusic/issues/40#issuecomment-526465755)_

已经回复过你[40#](https://github.com/maxlicheng/luci-app-unblockmusic/issues/40#issuecomment-526467331)

**Comment by admi-229133** [comment]
试过了 没用 我关闭了插件内存就回来了 还是等你来修复吧

**Comment by maxlicheng** [comment]
> 试过了 没用 我关闭了插件内存就回来了 还是等你来修复吧

什么路由器？目前只有你这边反馈内存会满，属于个例。你不运行插件它会满嘛？不生成日志也满那就跟日志没有关系，剩下的都是脚本程序，不会占用内存。

**Comment by admi-229133** [comment]
K2P MTK的版本 确实会内存满 你可以试试 我的华为安卓手机WIFI那设置手动代理 IP填路由的IP 端口填5200 本地绕过填localhost 这样子打开网易云音乐听歌内存就会刷刷的掉  本来有80M的运存很快就没了 我关闭插件内存就回来了 我也不知道是哪个问题

**Comment by maxlicheng** [comment]
并不是很清楚 本地绕过xxx，我的是新三，一天24小时开着插件，没有遇到过塞满内存的情况。自己并没有安卓机，建议换回L大的源码固件试试。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: admi-229133 <notifications@github.com&gt;
发送时间: 2019年8月30日 21:57
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 内存会满 (#43)




K2P MTK的版本 确实会内存满 你可以试试 我的华为安卓手机WIFI那设置手动代理 IP填路由的IP 端口填5200 本地绕过填localhost 这样子打开网易云音乐听歌内存就会刷刷的掉  本来有80M的运存很快就没了 我关闭插件内存就回来了 我也不知道是哪个问题

**Comment by smilence86** [comment]
同样k2t、k2p，内存占满，负载飙升，node进程占了大部分：
![image](https://user-images.githubusercontent.com/6102831/65216058-49f88a80-dae2-11e9-98f6-2f9d951eb24b.png)
  
kill -9 node进程恢复正常

k2t开启后直接无法使用，k2p还能用一会。

**Comment by maxlicheng** [comment]
> 同样k2t、k2p，内存占满，负载飙升，node进程占了大部分：
> ![image](https://user-images.githubusercontent.com/6102831/65216058-49f88a80-dae2-11e9-98f6-2f9d951eb24b.png)
> 
> kill -9 node进程恢复正常
> 
> k2t开启后直接无法使用，k2p还能用一会。

部分网友反映，K2系列的路由器跑node.js比较吃力。
