### ISSUE TITLE
程序是否有IP判断或者接口判断的功能

### ISSUE THREAD

**Issue by mlgexyz** [maxlicheng/luci-app-unblockmusic#44]
我程序放在从路由上，与主路由的连接方式为AP中继，断开WWAN接口（AP中继的那个接口）然后重新连接后，程序会自动重新启动，此功能是否可以手动关闭？

**Comment by maxlicheng** [comment]
插件脚本程序检测到app.js关键字就会判定程序正在运行，并没有判断ip的脚本。只要关闭了插件，正常来说是不会自动运行的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mlge <notifications@github.com&gt;
发送时间: 2019年8月30日 23:26
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 程序是否有IP判断或者接口判断的功能 (#44)




我程序放在从路由上，与主路由的连接方式为AP中继，断开WWAN接口（AP中继的那个接口）然后重新连接后，程序会自动重新启动，此功能是否可以手动关闭？
