### ISSUE TITLE
koolshare的lede中我升级了一下，无法启动

### ISSUE THREAD

**Issue by jinfeng1985** [maxlicheng/luci-app-unblockmusic#46]
日志如下图：

{ Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'music.httpdns.c.163.com',
  host: 'music.httpdns.c.163.com',
  port: 443 }

**Comment by maxlicheng** [comment]
卸载原插件后再安装试试。

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinfeng1985 <notifications@github.com&gt;
发送时间: 2019年9月2日 14:34
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)




日志如下图：

{ Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com:443
at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
errno: 'EAI_AGAIN',
code: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'music.httpdns.c.163.com',
host: 'music.httpdns.c.163.com',
port: 443 }

**Comment by jinfeng1985** [comment]
请问怎么卸载  我只按照教程会升级安装  卸载不会 = =！

**Comment by maxlicheng** [comment]
opkg remove luci-app-unblockmusic
opkg remove&nbsp;UnblockNeteaseMusic



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinfeng1985 <notifications@github.com&gt;
发送时间: 2019年9月2日 14:46
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)




请问怎么卸载  我只按照教程会升级安装  卸载不会 = =！

**Comment by jinfeng1985** [comment]
卸载重装 好像还是这样 一开始会提示运行中，一两秒后就提示未运行了，日志如一楼

**Comment by maxlicheng** [comment]
安装的是哪个版本？软路由可以正常上网不？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinfeng1985 <notifications@github.com&gt;
发送时间: 2019年9月2日 15:03
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)




卸载重装 好像还是这样 一开始会提示运行中，一两秒后就提示未运行了，日志如一楼

**Comment by jinfeng1985** [comment]
luci-app-unblockmusic_v2.2.0-1_all
UnblockNeteaseMusic_0.18.0-3_x86_64

路由器可以正常上网，lede版本是Openwrt Koolshare mod V2.32 r11575-bf5c725a70

**Comment by maxlicheng** [comment]
> 日志如下图：
> 
> { Error: getaddrinfo EAI_AGAIN music.httpdns.c.163.com:443
> at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
> errno: 'EAI_AGAIN',
> code: 'EAI_AGAIN',
> syscall: 'getaddrinfo',
> hostname: 'music.httpdns.c.163.com',
> host: 'music.httpdns.c.163.com',
> port: 443 }

@nondanee 大佬能看到这个issues嘛，这个问题一般是什么引起的，帮忙一起定位一下。

**Comment by nondanee** [comment]
启动时的 httpdns 请求挂掉了，可以自己往 hosts 写一个 ip 试试看
https://github.com/nondanee/UnblockNeteaseMusic/issues/216

https://tool.chinaz.com/speedtest.aspx?host=music.httpdns.c.163.com

**Comment by maxlicheng** [comment]
> 启动时的 httpdns 请求挂掉了，可以自己往 hosts 写一个 ip 试试看
> [nondanee/UnblockNeteaseMusic#216](https://github.com/nondanee/UnblockNeteaseMusic/issues/216)
> 
> https://tool.chinaz.com/speedtest.aspx?host=music.httpdns.c.163.com

相当于ping music.163.com得到的ip麽？
手动运行下面的命令？是这样操作嘛？
```
node /usr/share/UnblockNeteaseMusic/app.js -p 5200 -f 59.111.160.195
```

**Comment by nondanee** [comment]
@maxlicheng 不是
httpdns 是给移动端 VPN 性质的代理 (iOS 的 NetworkExtension，安卓的 VPNservice) 用的
和 `-f` 没关系

往 hosts 里写一个
```
223.252.199.66 music.httpdns.c.163.com
```
试试看

**Comment by jinfeng1985** [comment]
> @maxlicheng 不是
> httpdns 是给移动端 VPN 性质的代理 (iOS 的 NetworkExtension，安卓的 VPNservice) 用的
> 和 `-f` 没关系
> 
> @jinfeng1985
> 往 hosts 里写一个
> 
> ```
> 223.252.199.66 music.httpdns.c.163.com
> ```
> 
> 试试看

请问软路由里面怎么操作，我是新手

**Comment by jinfeng1985** [comment]
我直接去路由文件里面改了hosts 加了上面的  还是不行  需要重启路由器吗？

**Comment by maxlicheng** [comment]
> 我直接去路由文件里面改了hosts 加了上面的 还是不行 需要重启路由器吗？

试了下，koolshare v2.32版本确实不能正常运行。koolshare v2.31是正常的。
原因不明，感觉web界面上的保存与应用按钮未生效。
手动执行ssh命令确正常。
你试试
第一步：web界面 勾选 启动解锁，并点击保存与应用，此时应该还是红色，显示未运行；
第二步：ssh远程登录软路由后台，输入命令
```
/etc/init.d/unblockmusic start
```
通过以上两步即可使插件正常运行，web界面会显示绿色，“UnblockNeteaseMusic 运行中”；
取消运行也必须手动输入命令，执行命令后插件即停止运行
```
/etc/init.d/unblockmusic stop
```
以上操作务必保证安装了所有相关插件，并且路由器可以正常联通网络。
相关插件，注意安装顺利，缺一不可。
```
opkg install libopenssl_1.0.2p-1_x86_64.ipk
opkg install node_v8.16.0-1_x86_64.ipk
opkg install UnblockNeteaseMusic_0.18.0-3_x86_64.ipk
opkg install luci-app-unblockmusic_v2.2.0-1_all.ipk
```

**Comment by maxlicheng** [comment]
并且如果软路由没有连入网络，插件日志里边100%会出现如下提示(你所说的错误)。
![异常1](https://user-images.githubusercontent.com/40309661/64112095-fe8f6e00-cdb8-11e9-9a8e-31f234037107.jpg)

请务必确保，路由器 网络->诊断选项，可以正常ping通网络。
![报错1](https://user-images.githubusercontent.com/40309661/64111966-89239d80-cdb8-11e9-9c58-fc5bc4d39712.jpg)
![正常1](https://user-images.githubusercontent.com/40309661/64111976-8cb72480-cdb8-11e9-8d2e-e5f8748175fa.jpg)

**Comment by jinfeng1985** [comment]
1.按照手动开启服务方式我试了下，不行，插件都按顺序装过了。未升级的版本是可以开启的，但网易虽然不灰了，但双击是提示加载失败。
2.加host的方式也试过了，不行，ping也是OK的

**Comment by maxlicheng** [comment]
> 1.按照手动开启服务方式我试了下，不行，插件都按顺序装过了。未升级的版本是可以开启的，但网易虽然不灰了，但双击是提示加载失败。
> 2.加host的方式也试过了，不行，ping也是OK的

ssh后台ping music.163.com可以ping通嘛？
试试后台运行插件，截图看看打印的信息
```
node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
```
手动运行插件，客户端设备需要设置自动代理链接。

**Comment by jinfeng1985** [comment]
后台可以ping通，手动运行以上代码，显示：http server running@http://0.0.0.0:5200 但插件好像提示运行中了，安卓版好像还是灰色歌曲

**Comment by maxlicheng** [comment]
要输入代理链接，手动执行插件不会自动代理的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: jinfeng1985 <notifications@github.com&gt;
发送时间: 2019年9月2日 22:29
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)




后台可以ping通，手动运行以上代码，显示：http server running@http://0.0.0.0:5200 但插件好像提示运行中了，安卓版好像还是灰色歌曲

**Comment by nondanee** [comment]
后台 ping music.httpdns.c.163.com 通吗？

**Comment by jinfeng1985** [comment]
> 后台 ping music.httpdns.c.163.com 通吗？

可以ping通

**Comment by jinfeng1985** [comment]
手动代理设置后，灰色歌曲确实都显示了，但双击播放还是提示加载失败，播放其他歌曲去了

**Comment by nondanee** [comment]
@jinfeng1985 
ping 的通 music.httpdns.c.163.com 应该就不会报 EAI_AGAIN 错了吧？

加载失败原因很多，比如
iOS 可能就用不了 (我不太清楚)
音源可能挂掉了 (部分地区部分线路的问题，或者 cdn 的不按期望返回等等)

**Comment by maxlicheng** [comment]
路由器的一般是网易云的版本太新引起的，换个低版本试试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Nzix <notifications@github.com&gt;
发送时间: 2019年9月3日 22:37
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)




@jinfeng1985
 ping 的通 music.httpdns.c.163.com 应该就不会报 EAI_AGAIN 错了吧？
 
加载失败原因很多，比如
 iOS 可能就用不了 (我不太清楚)
 音源可能挂掉了 (部分地区部分线路的问题，或者 cdn 的不按期望返回等等)

**Comment by blankhang** [comment]
> > 我直接去路由文件里面改了hosts 加了上面的 还是不行 需要重启路由器吗？
> 
> 试了下，koolshare v2.32版本确实不能正常运行。koolshare v2.31是正常的。
> 原因不明，感觉web界面上的保存与应用按钮未生效。
> 手动执行ssh命令确正常。
> 你试试
> 第一步：web界面 勾选 启动解锁，并点击保存与应用，此时应该还是红色，显示未运行；
> 第二步：ssh远程登录软路由后台，输入命令
> 
> ```
> /etc/init.d/unblockmusic start
> ```
> 
> 通过以上两步即可使插件正常运行，web界面会显示绿色，“UnblockNeteaseMusic 运行中”；
> 取消运行也必须手动输入命令，执行命令后插件即停止运行
> 
> ```
> /etc/init.d/unblockmusic stop
> ```
> 
> 以上操作务必保证安装了所有相关插件，并且路由器可以正常联通网络。
> 相关插件，注意安装顺序，缺一不可。
> 
> ```
> opkg install libopenssl_1.0.2p-1_x86_64.ipk
> opkg install node_v8.16.0-1_x86_64.ipk
> opkg install UnblockNeteaseMusic_0.18.0-3_x86_64.ipk
> opkg install luci-app-unblockmusic_v2.2.0-1_all.ipk
> ```

LEDE 版本  Openwrt Koolshare mod V2.32 r11575-bf5c725a70
在按顺序安装这些软件后运行正常
你最新的releases没有放 libopenssl_1.0.2p-1_x86_64.ipk 我在https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.0 找了安装后运行正常

**Comment by maxlicheng** [comment]
好，谢谢反馈，我后面重新加一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: blankhang <notifications@github.com&gt;
发送时间: 2019年9月22日 17:45
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare的lede中我升级了一下，无法启动 (#46)



  
我直接去路由文件里面改了hosts 加了上面的 还是不行 需要重启路由器吗？
  
试了下，koolshare v2.32版本确实不能正常运行。koolshare v2.31是正常的。
 原因不明，感觉web界面上的保存与应用按钮未生效。
 手动执行ssh命令确正常。
 你试试
 第一步：web界面 勾选 启动解锁，并点击保存与应用，此时应该还是红色，显示未运行；
 第二步：ssh远程登录软路由后台，输入命令
 /etc/init.d/unblockmusic start  
通过以上两步即可使插件正常运行，web界面会显示绿色，“UnblockNeteaseMusic 运行中”；
 取消运行也必须手动输入命令，执行命令后插件即停止运行
 /etc/init.d/unblockmusic stop  
以上操作务必保证安装了所有相关插件，并且路由器可以正常联通网络。
 相关插件，注意安装顺序，缺一不可。
 opkg install libopenssl_1.0.2p-1_x86_64.ipk opkg install node_v8.16.0-1_x86_64.ipk opkg install UnblockNeteaseMusic_0.18.0-3_x86_64.ipk opkg install luci-app-unblockmusic_v2.2.0-1_all.ipk   
LEDE 版本  Openwrt Koolshare mod V2.32 r11575-bf5c725a70
 在按顺序安装这些软件后运行正常
 你最新的releases没有放 libopenssl_1.0.2p-1_x86_64.ipk 我在https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.0 找了安装后运行正常

**Comment by rufengsuixing** [comment]
这个问题是因为保留配置文件升级导致的，lean大的配置文件里没有lport还是hport这个参数，启动时参数为空就炸了

**Comment by maxlicheng** [comment]
> 这个问题是因为保留配置文件升级导致的，lean大的配置文件里没有lport还是hport这个参数，启动时参数为空就炸了

已经本插件的端口号直接写入脚本中，不再从配置文件中获取。

**Comment by maxlicheng** [comment]
> > > 我直接去路由文件里面改了hosts 加了上面的 还是不行 需要重启路由器吗？
> > 
> > 
> > 试了下，koolshare v2.32版本确实不能正常运行。koolshare v2.31是正常的。
> > 原因不明，感觉web界面上的保存与应用按钮未生效。
> > 手动执行ssh命令确正常。
> > 你试试
> > 第一步：web界面 勾选 启动解锁，并点击保存与应用，此时应该还是红色，显示未运行；
> > 第二步：ssh远程登录软路由后台，输入命令
> > ```
> > /etc/init.d/unblockmusic start
> > ```
> > 
> > 
> > 通过以上两步即可使插件正常运行，web界面会显示绿色，“UnblockNeteaseMusic 运行中”；
> > 取消运行也必须手动输入命令，执行命令后插件即停止运行
> > ```
> > /etc/init.d/unblockmusic stop
> > ```
> > 
> > 
> > 以上操作务必保证安装了所有相关插件，并且路由器可以正常联通网络。
> > 相关插件，注意安装顺序，缺一不可。
> > ```
> > opkg install libopenssl_1.0.2p-1_x86_64.ipk
> > opkg install node_v8.16.0-1_x86_64.ipk
> > opkg install UnblockNeteaseMusic_0.18.0-3_x86_64.ipk
> > opkg install luci-app-unblockmusic_v2.2.0-1_all.ipk
> > ```
> 
> LEDE 版本 Openwrt Koolshare mod V2.32 r11575-bf5c725a70
> 在按顺序安装这些软件后运行正常
> 你最新的releases没有放 libopenssl_1.0.2p-1_x86_64.ipk 我在https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.0 找了安装后运行正常

已在新的发行版中加入linopenssl ipk
