### ISSUE TITLE
openwrt

### ISSUE THREAD

**Issue by qq616852877** [maxlicheng/luci-app-unblockmusic#48]

**Comment by qq616852877** [comment]
编译的OpenWrt R9.8.17，平台是Atheros AR9344 rev 2，然后开启lean源自带的解锁插件，cpu会长期占用百分百，这个有解决办法么

**Comment by maxlicheng** [comment]
> 编译的OpenWrt R9.8.17，平台是Atheros AR9344 rev 2，然后开启lean源自带的解锁插件，cpu会长期占用百分百，这个有解决办法么

后台手动运行启动命令试试
```
node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
```

**Comment by maxlicheng** [comment]
> 编译的OpenWrt R9.8.17，平台是Atheros AR9344 rev 2，然后开启lean源自带的解锁插件，cpu会长期占用百分百，这个有解决办法么

也可能这颗主控芯片性能一般，跑node.js太吃力了。
