### ISSUE TITLE
能不能发布一个贝壳云op能用的ipk

### ISSUE THREAD

**Issue by zhangyongkuanhan** [maxlicheng/luci-app-unblockmusic#49]
Openwrt-mix_5.75_Meibeike.img，内核版本4.4.174
https://yun.baidu.com/s/1SkCX2kbdtpn5brfeKdaBjA
提取码pypy
终端默认账号：root 密码：password

**Comment by maxlicheng** [comment]
> Openwrt-mix_5.75_Meibeike.img，内核版本4.4.174
> https://yun.baidu.com/s/1SkCX2kbdtpn5brfeKdaBjA
> 提取码pypy
> 终端默认账号：root 密码：password

身边没有这种设备，需要你自己编译安装体验。
