### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by cdcvip** [maxlicheng/luci-app-unblockmusic#50]
{ Error: connect ETIMEDOUT 59.111.179.213:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '59.111.179.213',
  port: 443 }

**Comment by maxlicheng** [comment]
> > > { Error: connect ETIMEDOUT 59.111.179.213:443
> > > at Object._errnoException (util.js:1022:11)
> > > at _exceptionWithHostPort (util.js:1044:20)
> > > at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
> > > code: 'ETIMEDOUT',
> > > errno: 'ETIMEDOUT',
> > > syscall: 'connect',
> > > address: '59.111.179.213',
> > > port: 443 }
> > 
> > 
> > UnblockNeteaseMusic 更新至v0.19.2，修复插件httpdns v2请求异常问题，请git clone插件源码编译后安装体验。
> 
> @maxlicheng 没有为x86_64版koolshare编译的版本？

已上传，查看[release v2.2.0-1](https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.0-1)
