### ISSUE TITLE
n1旁路由自动代理不成功

### ISSUE THREAD

**Issue by liucan12138** [maxlicheng/luci-app-unblockmusic#52]
n1作为旁路由，k2p作为主路由，电脑或者手机都不能自动代理，电脑上网易云客户端手动设置代理倒是可以成功，有什么解决办法吗？

**Comment by maxlicheng** [comment]
> n1作为旁路由，k2p作为主路由，电脑或者手机都不能自动代理，电脑上网易云客户端手动设置代理倒是可以成功，有什么解决办法吗？

默认是192.168.x.1为代理ip，你尝试一下n1的ip为x.1，k2p改其他。

**Comment by liucan12138** [comment]
> > N1作为旁路由，K2P作为主路由，电脑或者手机都不能自动代理，电脑上网易云客户端手动设置代理倒是可以成功，有什么解决办法吗？
> 
> 默认是192.168.x.1为代理IP，你尝试一下N1的IP为X.1，K2P改其他。

好的，我试试

**Comment by ihuaer** [comment]
> n1作为旁路由，k2p作为主路由，电脑或者手机都不能自动代理，电脑上网易云客户端手动设置代理倒是可以成功，有什么解决办法吗？

手动填写代理，ip填写n1的ip

**Comment by LunaticTian** [comment]
> > n1 作为旁路由，k2p 作为主路由，电脑或者手机都不能自动代理，电脑上网易云客户端手动设置代理倒是可以成功，有什么解决办法吗？
> 
> 默认是 192.168.x.1 为代理 ip，你尝试一下 n1 的 ip 为 x.1，k2p 改其他。

请问源码中哪里可以修改默认代理ip，我找了半天没有找到....
