### ISSUE TITLE
Lede X64 V2.32自带的APP如何更新

### ISSUE THREAD

**Issue by Meow1688** [maxlicheng/luci-app-unblockmusic#56]
请问下如何更新Lede X64 V2.32自带的解锁工具啊

**Comment by maxlicheng** [comment]
koolshare麽？下载新版(具体见release)，依次安装即可。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Meow1688 <notifications@github.com&gt;
发送时间: 2019年9月28日 23:38
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)




请问下如何更新Lede X64 V2.32自带的解锁工具啊

**Comment by Meow1688** [comment]
需要先卸载原来的么

**Comment by maxlicheng** [comment]
不用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MIAOBUSI <notifications@github.com&gt;
发送时间: 2019年9月28日 23:53
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)




需要先卸载原来的么

**Comment by Meow1688** [comment]
好的谢谢。。我先去安装试试。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: maxlicheng <notifications@github.com>
发送时间: Saturday, September 28, 2019 11:54:42 PM
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com>
抄送: MIAOBUSI <cc27zq98@outlook.com>; Author <author@noreply.github.com>
主题: Re: [maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)

不用



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MIAOBUSI <notifications@github.com&gt;
发送时间: 2019年9月28日 23:53
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)




需要先卸载原来的么

―
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

―

**Comment by Meow1688** [comment]
已经更新好了。。可是勾选打开后是未运行状态 明明已经勾选打开和应用了

**Comment by Meow1688** [comment]
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/bin/node)
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/bin/node)
Error relocating /usr/bin/node: EVP_get_digestbyname: symbol not found
Error relocating /usr/bin/node: EC_KEY_generate_key: symbol not found
Error relocating /usr/bin/node: ENGINE_set_default: symbol not found
Error relocating /usr/bin/node: BN_cmp: symbol not found
Error relocating /usr/bin/node: SSL_COMP_get_compression_methods: symbol not found
Error relocating /usr/bin/node: BN_new: symbol not found
Error relocating /usr/bin/node: ERR_error_string_n: symbol not found
Error relocating /usr/bin/node: EC_KEY_get0_group: symbol not found
Error relocating /usr/bin/node: ENGINE_free: symbol not found
Error relocating /usr/bin/node: EVP_EncryptInit_ex: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_DHparams: symbol not found
Error relocating /usr/bin/node: SSL_get_peer_cert_chain: symbol not found
Error relocating /usr/bin/node: CRYPTO_memcmp: symbol not found
Error relocating /usr/bin/node: X509_STORE_CTX_free: symbol not found
Error relocating /usr/bin/node: EVP_sha1: symbol not found
Error relocating /usr/bin/node: X509V3_EXT_d2i: symbol not found
Error relocating /usr/bin/node: sk_new: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_next_protos_advertised_cb: symbol not found
Error relocating /usr/bin/node: ERR_pop_to_mark: symbol not found
Error relocating /usr/bin/node: X509_get_issuer_name: symbol not found
Error relocating /usr/bin/node: OPENSSL_load_builtin_modules: symbol not found
Error relocating /usr/bin/node: X509V3_EXT_get: symbol not found
Error relocating /usr/bin/node: BIO_read: symbol not found
Error relocating /usr/bin/node: SSL_CTX_add_client_CA: symbol not found
Error relocating /usr/bin/node: BIO_set_flags: symbol not found
Error relocating /usr/bin/node: EVP_DigestFinal_ex: symbol not found
Error relocating /usr/bin/node: ENGINE_by_id: symbol not found
Error relocating /usr/bin/node: NETSCAPE_SPKI_b64_decode: symbol not found
Error relocating /usr/bin/node: sk_delete: symbol not found
Error relocating /usr/bin/node: BIO_new: symbol not found
Error relocating /usr/bin/node: EC_KEY_set_public_key: symbol not found
Error relocating /usr/bin/node: ASN1_TIME_print: symbol not found
Error relocating /usr/bin/node: TLSv1_client_method: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_get1_EC_KEY: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_decrypt: symbol not found
Error relocating /usr/bin/node: EC_POINT_point2oct: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_flags: symbol not found
Error relocating /usr/bin/node: HMAC_CTX_cleanup: symbol not found
Error relocating /usr/bin/node: SSL_get_current_cipher: symbol not found
Error relocating /usr/bin/node: ERR_load_ENGINE_strings: symbol not found
Error relocating /usr/bin/node: DH_new: symbol not found
Error relocating /usr/bin/node: EVP_CipherFinal_ex: symbol not found
Error relocating /usr/bin/node: TLSv1_1_method: symbol not found
Error relocating /usr/bin/node: SSL_CTX_sess_set_get_cb: symbol not found
Error relocating /usr/bin/node: EVP_sha256: symbol not found
Error relocating /usr/bin/node: SSL_get_verify_result: symbol not found
Error relocating /usr/bin/node: HMAC_CTX_init: symbol not found
Error relocating /usr/bin/node: EVP_MD_CTX_md: symbol not found
Error relocating /usr/bin/node: RAND_poll: symbol not found
Error relocating /usr/bin/node: SSL_CTX_new: symbol not found
Error relocating /usr/bin/node: SSL_set_SSL_CTX: symbol not found
Error relocating /usr/bin/node: OBJ_sn2nid: symbol not found
Error relocating /usr/bin/node: SSL_get_version: symbol not found
Error relocating /usr/bin/node: BIO_ctrl: symbol not found
Error relocating /usr/bin/node: BIO_clear_flags: symbol not found
Error relocating /usr/bin/node: SSL_CTX_use_PrivateKey: symbol not found
Error relocating /usr/bin/node: TLSv1_2_client_method: symbol not found
Error relocating /usr/bin/node: SSL_CIPHER_get_name: symbol not found
Error relocating /usr/bin/node: SSL_set_verify: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_sign: symbol not found
Error relocating /usr/bin/node: X509V3_EXT_print: symbol not found
Error relocating /usr/bin/node: SSL_renegotiate: symbol not found
Error relocating /usr/bin/node: X509_STORE_set_flags: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_set1_RSA: symbol not found
Error relocating /usr/bin/node: TLSv1_1_server_method: symbol not found
Error relocating /usr/bin/node: SSL_shutdown: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_iv_length: symbol not found
Error relocating /usr/bin/node: BN_bn2bin: symbol not found
Error relocating /usr/bin/node: HMAC_Init_ex: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_session_id_context: symbol not found
Error relocating /usr/bin/node: SSL_set_alpn_protos: symbol not found
Error relocating /usr/bin/node: X509_digest: symbol not found
Error relocating /usr/bin/node: SSL_set_ex_data: symbol not found
Error relocating /usr/bin/node: SSL_get_session: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_id: symbol not found
Error relocating /usr/bin/node: BN_set_word: symbol not found
Error relocating /usr/bin/node: X509_get_ext: symbol not found
Error relocating /usr/bin/node: EC_POINT_free: symbol not found
Error relocating /usr/bin/node: ERR_set_mark: symbol not found
Error relocating /usr/bin/node: NETSCAPE_SPKI_get_pubkey: symbol not found
Error relocating /usr/bin/node: X509_STORE_CTX_init: symbol not found
Error relocating /usr/bin/node: SSL_get_error: symbol not found
Error relocating /usr/bin/node: X509_STORE_CTX_new: symbol not found
Error relocating /usr/bin/node: CRYPTO_THREADID_set_pointer: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_PrivateKey: symbol not found
Error relocating /usr/bin/node: SSL_CTX_ctrl: symbol not found
Error relocating /usr/bin/node: SSL_get_ex_data: symbol not found
Error relocating /usr/bin/node: X509_dup: symbol not found
Error relocating /usr/bin/node: SSL_dup_CA_list: symbol not found
Error relocating /usr/bin/node: X509_STORE_add_cert: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_verify_recover_init: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_cipher_list: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_CTX_free: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_bits: symbol not found
Error relocating /usr/bin/node: EC_KEY_set_private_key: symbol not found
Error relocating /usr/bin/node: SSL_set_connect_state: symbol not found
Error relocating /usr/bin/node: SSL_set_bio: symbol not found
Error relocating /usr/bin/node: sk_pop_free: symbol not found
Error relocating /usr/bin/node: EVP_CipherInit_ex: symbol not found
Error relocating /usr/bin/node: sk_new_null: symbol not found
Error relocating /usr/bin/node: SSL_get_ciphers: symbol not found
Error relocating /usr/bin/node: SSL_CTX_use_certificate: symbol not found
Error relocating /usr/bin/node: ENGINE_load_builtin_engines: symbol not found
Error relocating /usr/bin/node: EC_GROUP_get_curve_name: symbol not found
Error relocating /usr/bin/node: ERR_peek_last_error: symbol not found
Error relocating /usr/bin/node: SSLv23_method: symbol not found
Error relocating /usr/bin/node: sk_zero: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_set_key_length: symbol not found
Error relocating /usr/bin/node: BIO_free: symbol not found
Error relocating /usr/bin/node: X509_PUBKEY_get: symbol not found
Error relocating /usr/bin/node: BN_print: symbol not found
Error relocating /usr/bin/node: DH_generate_parameters_ex: symbol not found
Error relocating /usr/bin/node: EC_POINT_oct2point: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_PUBKEY: symbol not found
Error relocating /usr/bin/node: DH_size: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_free: symbol not found
Error relocating /usr/bin/node: NETSCAPE_SPKI_verify: symbol not found
Error relocating /usr/bin/node: ERR_reason_error_string: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_CTX_new: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_set_padding: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_X509_AUX: symbol not found
Error relocating /usr/bin/node: i2d_SSL_SESSION: symbol not found
Error relocating /usr/bin/node: EVP_aes_128_cbc: symbol not found
Error relocating /usr/bin/node: ERR_error_string: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_ex_data: symbol not found
Error relocating /usr/bin/node: CONF_modules_load_file: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_encrypt: symbol not found
Error relocating /usr/bin/node: SSL_ctrl: symbol not found
Error relocating /usr/bin/node: SSLv23_client_method: symbol not found
Error relocating /usr/bin/node: X509_get_ext_by_NID: symbol not found
Error relocating /usr/bin/node: SSL_set_client_CA_list: symbol not found
Error relocating /usr/bin/node: BN_bin2bn: symbol not found
Error relocating /usr/bin/node: DH_compute_key: symbol not found
Error relocating /usr/bin/node: ERR_peek_error: symbol not found
Error relocating /usr/bin/node: SSL_read: symbol not found
Error relocating /usr/bin/node: TLSv1_1_client_method: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_timeout: symbol not found
Error relocating /usr/bin/node: BIO_free_all: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_new: symbol not found
Error relocating /usr/bin/node: SSL_CTX_get0_certificate: symbol not found
Error relocating /usr/bin/node: EVP_md5: symbol not found
Error relocating /usr/bin/node: SSL_get_servername: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_cert_store: symbol not found
Error relocating /usr/bin/node: BIO_s_mem: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_CTX_ctrl: symbol not found
Error relocating /usr/bin/node: DH_check_pub_key: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_verify_recover: symbol not found
Error relocating /usr/bin/node: SSL_get_shutdown: symbol not found
Error relocating /usr/bin/node: SSL_load_error_strings: symbol not found
Error relocating /usr/bin/node: SSL_select_next_proto: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_RSAPublicKey: symbol not found
Error relocating /usr/bin/node: RAND_status: symbol not found
Error relocating /usr/bin/node: SSL_CTX_get_client_CA_list: symbol not found
Error relocating /usr/bin/node: SSL_library_init: symbol not found
Error relocating /usr/bin/node: SSL_connect: symbol not found
Error relocating /usr/bin/node: BN_num_bits: symbol not found
Error relocating /usr/bin/node: OPENSSL_add_all_algorithms_noconf: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_flags: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_cipher: symbol not found
Error relocating /usr/bin/node: X509_get_subject_name: symbol not found
Error relocating /usr/bin/node: X509_STORE_CTX_get1_issuer: symbol not found
Error relocating /usr/bin/node: HMAC_Update: symbol not found
Error relocating /usr/bin/node: SSL_use_PrivateKey: symbol not found
Error relocating /usr/bin/node: EVP_MD_CTX_destroy: symbol not found
Error relocating /usr/bin/node: SSL_CTX_get0_privatekey: symbol not found
Error relocating /usr/bin/node: TLSv1_method: symbol not found
Error relocating /usr/bin/node: EC_KEY_check_key: symbol not found
Error relocating /usr/bin/node: X509V3_EXT_get_nid: symbol not found
Error relocating /usr/bin/node: TLSv1_server_method: symbol not found
Error relocating /usr/bin/node: X509_STORE_new: symbol not found
Error relocating /usr/bin/node: SSL_use_certificate: symbol not found
Error relocating /usr/bin/node: PKCS12_free: symbol not found
Error relocating /usr/bin/node: EVP_BytesToKey: symbol not found
Error relocating /usr/bin/node: ASN1_STRING_to_UTF8: symbol not found
Error relocating /usr/bin/node: EVP_MD_do_all_sorted: symbol not found
Error relocating /usr/bin/node: SSL_write: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_free: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_do_all_sorted: symbol not found
Error relocating /usr/bin/node: SSLv23_server_method: symbol not found
Error relocating /usr/bin/node: SSL_get0_alpn_selected: symbol not found
Error relocating /usr/bin/node: SSL_get_finished: symbol not found
Error relocating /usr/bin/node: i2v_GENERAL_NAME: symbol not found
Error relocating /usr/bin/node: PEM_write_bio_PUBKEY: symbol not found
Error relocating /usr/bin/node: X509_CRL_free: symbol not found
Error relocating /usr/bin/node: SSL_free: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_verify_init: symbol not found
Error relocating /usr/bin/node: TLSv1_2_method: symbol not found
Error relocating /usr/bin/node: SSL_new: symbol not found
Error relocating /usr/bin/node: BN_bn2hex: symbol not found
Error relocating /usr/bin/node: sk_num: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_new: symbol not found
Error relocating /usr/bin/node: X509V3_conf_free: symbol not found
Error relocating /usr/bin/node: X509_STORE_add_crl: symbol not found
Error relocating /usr/bin/node: X509_get_pubkey: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_X509_CRL: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_verify: symbol not found
Error relocating /usr/bin/node: CRYPTO_set_locking_callback: symbol not found
Error relocating /usr/bin/node: EC_GROUP_get_degree: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_ctrl: symbol not found
Error relocating /usr/bin/node: SSL_set_accept_state: symbol not found
Error relocating /usr/bin/node: SSL_state: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_set_flags: symbol not found
Error relocating /usr/bin/node: SSL_set_session: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_next_proto_select_cb: symbol not found
Error relocating /usr/bin/node: EC_GROUP_get_order: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_sign_init: symbol not found
Error relocating /usr/bin/node: SSL_CTX_sess_set_new_cb: symbol not found
Error relocating /usr/bin/node: SSL_CTX_callback_ctrl: symbol not found
Error relocating /usr/bin/node: RSA_free: symbol not found
Error relocating /usr/bin/node: OBJ_nid2sn: symbol not found
Error relocating /usr/bin/node: GENERAL_NAME_free: symbol not found
Error relocating /usr/bin/node: ASN1_INTEGER_to_BN: symbol not found
Error relocating /usr/bin/node: X509_check_issued: symbol not found
Error relocating /usr/bin/node: X509_get_serialNumber: symbol not found
Error relocating /usr/bin/node: PKCS12_parse: symbol not found
Error relocating /usr/bin/node: RAND_bytes: symbol not found
Error relocating /usr/bin/node: sk_value: symbol not found
Error relocating /usr/bin/node: EVP_MD_CTX_create: symbol not found
Error relocating /usr/bin/node: SSL_CTX_get_cert_store: symbol not found
Error relocating /usr/bin/node: BIO_new_file: symbol not found
Error relocating /usr/bin/node: BIO_new_mem_buf: symbol not found
Error relocating /usr/bin/node: BN_free: symbol not found
Error relocating /usr/bin/node: TLSv1_2_server_method: symbol not found
Error relocating /usr/bin/node: BIO_test_flags: symbol not found
Error relocating /usr/bin/node: EVP_CipherUpdate: symbol not found
Error relocating /usr/bin/node: OBJ_obj2txt: symbol not found
Error relocating /usr/bin/node: ENGINE_ctrl_cmd_string: symbol not found
Error relocating /usr/bin/node: FIPS_mode: symbol not found
Error relocating /usr/bin/node: NETSCAPE_SPKI_free: symbol not found
Error relocating /usr/bin/node: HMAC_Final: symbol not found
Error relocating /usr/bin/node: EC_KEY_free: symbol not found
Error relocating /usr/bin/node: SSL_set_info_callback: symbol not found
Error relocating /usr/bin/node: BIO_printf: symbol not found
Error relocating /usr/bin/node: OPENSSL_cleanse: symbol not found
Error relocating /usr/bin/node: X509_free: symbol not found
Error relocating /usr/bin/node: ERR_print_errors: symbol not found
Error relocating /usr/bin/node: SSL_SESSION_free: symbol not found
Error relocating /usr/bin/node: EVP_DigestUpdate: symbol not found
Error relocating /usr/bin/node: EVP_get_cipherbyname: symbol not found
Error relocating /usr/bin/node: SSL_set_cert_cb: symbol not found
Error relocating /usr/bin/node: X509_STORE_set_default_paths: symbol not found
Error relocating /usr/bin/node: sk_push: symbol not found
Error relocating /usr/bin/node: SSL_get_peer_certificate: symbol not found
Error relocating /usr/bin/node: X509_get_ext_d2i: symbol not found
Error relocating /usr/bin/node: SSL_CTX_free: symbol not found
Error relocating /usr/bin/node: EC_KEY_get0_private_key: symbol not found
Error relocating /usr/bin/node: ERR_clear_error: symbol not found
Error relocating /usr/bin/node: EC_KEY_get0_public_key: symbol not found
Error relocating /usr/bin/node: SSL_SESSION_get_id: symbol not found
Error relocating /usr/bin/node: CRYPTO_num_locks: symbol not found
Error relocating /usr/bin/node: EC_POINT_new: symbol not found
Error relocating /usr/bin/node: BIO_write: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_get1_RSA: symbol not found
Error relocating /usr/bin/node: DH_free: symbol not found
Error relocating /usr/bin/node: EC_get_builtin_curves: symbol not found
Error relocating /usr/bin/node: SSL_CTX_get_ex_data: symbol not found
Error relocating /usr/bin/node: DH_check: symbol not found
Error relocating /usr/bin/node: X509_NAME_print_ex: symbol not found
Error relocating /usr/bin/node: ERR_get_error: symbol not found
Error relocating /usr/bin/node: d2i_SSL_SESSION: symbol not found
Error relocating /usr/bin/node: PEM_read_bio_X509: symbol not found
Error relocating /usr/bin/node: EC_POINT_mul: symbol not found
Error relocating /usr/bin/node: SSL_get_SSL_CTX: symbol not found
Error relocating /usr/bin/node: i2d_X509: symbol not found
Error relocating /usr/bin/node: OPENSSL_no_config: symbol not found
Error relocating /usr/bin/node: X509_verify_cert_error_string: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_size: symbol not found
Error relocating /usr/bin/node: d2i_PKCS12_bio: symbol not found
Error relocating /usr/bin/node: BN_value_one: symbol not found
Error relocating /usr/bin/node: EVP_CIPHER_CTX_block_size: symbol not found
Error relocating /usr/bin/node: CRYPTO_free: symbol not found
Error relocating /usr/bin/node: EVP_DecryptInit_ex: symbol not found
Error relocating /usr/bin/node: X509V3_EXT_val_prn: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_decrypt_init: symbol not found
Error relocating /usr/bin/node: BN_get_word: symbol not found
Error relocating /usr/bin/node: DH_generate_key: symbol not found
Error relocating /usr/bin/node: CRYPTO_THREADID_set_callback: symbol not found
Error relocating /usr/bin/node: SSL_get_peer_finished: symbol not found
Error relocating /usr/bin/node: ASN1_OBJECT_free: symbol not found
Error relocating /usr/bin/node: EVP_PKEY_encrypt_init: symbol not found
Error relocating /usr/bin/node: EC_KEY_new_by_curve_name: symbol not found
Error relocating /usr/bin/node: ECDH_compute_key: symbol not found
Error relocating /usr/bin/node: EVP_DigestInit_ex: symbol not found
Error relocating /usr/bin/node: SSL_accept: symbol not found
Error relocating /usr/bin/node: CRYPTO_add_lock: symbol not found
Error relocating /usr/bin/node: SSL_get0_next_proto_negotiated: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_alpn_select_cb: symbol not found
Error relocating /usr/bin/node: PKCS5_PBKDF2_HMAC: symbol not found


这是日志。。node我已经安装了

**Comment by maxlicheng** [comment]
下载这个压缩包[koolshare-x86_64-luci-app-unblockmusic-v2.1.0.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.1.0/koolshare-x86_64-luci-app-unblockmusic-v2.1.0.zip)，解压后安装 libopenssl_1.0.2p-1_x86_64.ipk

**Comment by Meow1688** [comment]
我试试。。谢谢。。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: maxlicheng <notifications@github.com>
发送时间: Sunday, September 29, 2019 12:18:30 AM
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com>
抄送: MIAOBUSI <cc27zq98@outlook.com>; Author <author@noreply.github.com>
主题: Re: [maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)


下载这个压缩包koolshare-x86_64-luci-app-unblockmusic-v2.1.0.zip<https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.1.0/koolshare-x86_64-luci-app-unblockmusic-v2.1.0.zip>，解压后安装 libopenssl_1.0.2p-1_x86_64.ipk

―

**Comment by Meow1688** [comment]
谢谢dalao。。现在macOS和Windows还有Android都已经可以正常使用了。。就是iOS已解锁可是提示网络不给力，无法继续播放

**Comment by maxlicheng** [comment]
ios安装低版本了嘛？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MIAOBUSI <notifications@github.com&gt;
发送时间: 2019年9月29日 00:57
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)




谢谢dalao。。现在macOS和Windows还有Android都已经可以正常使用了。。就是iOS已解锁可是提示网络不给力，无法继续播放

**Comment by Meow1688** [comment]
安装了 还是不行

发自我的iPhone

在 2019年9月29日，08:25，maxlicheng <notifications@github.com> 写道：

﻿ios安装低版本了嘛？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: MIAOBUSI <notifications@github.com&gt;
发送时间: 2019年9月29日 00:57
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] Lede X64 V2.32自带的APP如何更新 (#56)




谢谢dalao。。现在macOS和Windows还有Android都已经可以正常使用了。。就是iOS已解锁可是提示网络不给力，无法继续播放
