### ISSUE TITLE
koolshare 更新了LEDE_X64，内核版本升级至4.19.75，自带的解锁灰色音乐无法启动

### ISSUE THREAD

**Issue by WXLmjr** [maxlicheng/luci-app-unblockmusic#58]
折腾了半天也没有编译成功，怎奈经验不足，还望作者提供相应的版本，谢谢！

**Comment by maxlicheng** [comment]
> 折腾了半天也没有编译成功，怎奈经验不足，还望作者提供相应的版本，谢谢！

用这个[x86.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0-1/x86.zip)，按里面的说明文档进行安装即可。

**Comment by QiuSimons** [comment]
> > 折腾了半天也没有编译成功，怎奈经验不足，还望作者提供相应的版本，谢谢！
> 
> 用这个[x86.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.0-1/x86.zip)，按里面的说明文档进行安装即可。

大佬，最新的2.2.2是不是忘记更新ipk了啊？

**Comment by maxlicheng** [comment]
假期回家了，返程回来后又想着实现在线更新，没有编译ipk了，你可以自己尝试编译一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: QiuSimons <notifications@github.com&gt;
发送时间: 2019年10月8日 17:48
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare 更新了LEDE_X64，内核版本升级至4.19.75，自带的解锁灰色音乐无法启动 (#58)



  
折腾了半天也没有编译成功，怎奈经验不足，还望作者提供相应的版本，谢谢！
  
用这个x86.zip，按里面的说明文档进行安装即可。
  
大佬，最新的2.2.2是不是忘记更新ipk了啊？
