### ISSUE TITLE
未运行

### ISSUE THREAD

**Issue by RealKiro** [maxlicheng/luci-app-unblockmusic#59]
1. 未运行
![image](https://user-images.githubusercontent.com/33367701/66252294-6eb05b80-e78c-11e9-8c33-0de07bcb6fd7.png)
![image](https://user-images.githubusercontent.com/33367701/66252297-7bcd4a80-e78c-11e9-8742-faed560f3809.png)

2. UnblockNeteaseMusic更新建议参考  [Lean](https://github.com/coolsnowwolf/lede/blob/master/package/lean/UnblockNeteaseMusic/Makefile) 或 [project-openwrt](https://github.com/project-openwrt/luci-app-unblockneteasemusic/blob/6158f9336faa43d7882b95ba6c877e2faa2b8d27/UnblockNeteaseMusic-nondanee/Makefile) 这2种方式，因为releases跟不上作者源码修复速度

**Comment by maxlicheng** [comment]
1.日志显示端口参数不对，应该是配置文件少了个hport参数，你检查一下。
2.正有这打算，好，这几天更新一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 未日 <notifications@github.com&gt;
发送时间: 2019年10月5日 16:31
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 未运行 (#59)





未运行





UnblockNeteaseMusic更新建议参考  Lean 或 project-openwrt 这2种方式，因为releases跟不上作者源码修复速度
