### ISSUE TITLE
ios好像有问题

### ISSUE THREAD

**Issue by Hwkyzie** [maxlicheng/luci-app-unblockmusic#6]
我安卓测试了可以听可以下载   IOS无法听无法下载

**Comment by maxlicheng** [comment]
那说明是ios的问题，不是源码的问题，ios方面的问题。这里有三种方式，你看一下哪三种适合你，代理使用的方式：源码说明里面的ip 与 端口 是一种，博客里面的是url链接另一种，还有一种是用小飞机的代理，会复杂一点，你可以去研究一下。
