### ISSUE TITLE
安卓app部分图片加载失败

### ISSUE THREAD

**Issue by binsee** [maxlicheng/luci-app-unblockmusic#62]
## 问题
安卓客户端 v6.4.2
加载部分歌单图片失败
![image](https://user-images.githubusercontent.com/5285894/66259396-30925680-e7e3-11e9-8839-853922f5d654.png)

## 分析
https://github.com/maxlicheng/luci-app-unblockmusic/blob/e0aac69e32515f13218a7b48831a83f296fdc6f7/app/root/etc/init.d/unblockmusic#L21
在脚本中，使用httpdns解析如下域名：
```
p2.music.126.net
interface.music.163.com
interface3.music.163.com
clientlog.music.163.com
apm.music.163.com
apm3.music.163.com
p1.music.126.net
clientlog3.music.163.com
```

其中，`p1.music.126.net`和`p2.music.126.net`是cdn域名主要用于加载图片。
而**unblockmusic**中，这两个域名是不在代理域名列表中的。

根据代码https://github.com/nondanee/UnblockNeteaseMusic/blob/626253f0b9a32bd793b9ceb04043202591954562/hook.js#L69
```
hook.target.host = [
	'music.163.com',
	'interface.music.163.com',
	'interface3.music.163.com',
	'apm.music.163.com',
	'apm3.music.163.com',
	// 'mam.netease.com',
	// 'api.iplay.163.com', // look living
	// 'ac.dun.163yun.com',
	// 'crash.163.com',
	// 'clientlog.music.163.com',
	// 'clientlog3.music.163.com'
]
// ...........
req.url = (req.url.startsWith('http://') ? '' : (req.socket.encrypted ? 'https:' : 'http:') + '//' + (hook.target.host.includes(req.headers.host) ? req.headers.host : null)) + req.url
```
不在列表中的域名会被替换为`null`，即此访问会失败，导致对`p1.music.126.net`域名的访问失败，即图片加载失败。

> 关于替换为`null`的原因，**nondanee** 在此进行了解释， https://github.com/nondanee/UnblockNeteaseMusic/issues/263#issuecomment-538665166

## 解决方式
从httpdns解析的目标中，去掉 `p1.music.126.net`和`p2.music.126.net`，之后正常

**Comment by maxlicheng** [comment]
@binsee 感谢您的优化，测试无异常，已将您提交的源码合并。
