### ISSUE TITLE
老大请进

### ISSUE THREAD

**Issue by chiyu521** [maxlicheng/luci-app-unblockmusic#64]
我用官方的19.07 没办法使用unblockmusic 在make menuconfig 的LUCI APP里找不到~~
不知道是什么原因 NODE我已经装载了

**Comment by maxlicheng** [comment]
在源码中能找到node选项嘛？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chiyu521 <notifications@github.com&gt;
发送时间: 2019年10月6日 12:30
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 老大请进 (#64)




我用官方的19.07 没办法使用unblockmusic 在make menuconfig 的LUCI APP里找不到~~
不知道是什么原因 NODE我已经装载了

**Comment by maxlicheng** [comment]
> 我用官方的19.07 没办法使用unblockmusic 在make menuconfig 的LUCI APP里找不到~~
> 不知道是什么原因 NODE我已经装载了

进入make menuconfig查看，Langages ---> Node.js --->查看Node.js选项中是否有可选项，如无说明你的路由器不支持Node.js。

**Comment by maxlicheng** [comment]
> 我用官方的19.07 没办法使用unblockmusic 在make menuconfig 的LUCI APP里找不到~~
> 不知道是什么原因 NODE我已经装载了

经测试，[[官方最新源码]](https://github.com/openwrt/openwrt)是支持本插件的。
![image](https://user-images.githubusercontent.com/40309661/66281470-15603d80-e8ee-11e9-8037-5ca0d5e56df2.png)

**Comment by chiyu521** [comment]
make menuconfig&nbsp;里是可以找到NODE.JS的~

**Comment by maxlicheng** [comment]
> make menuconfig&nbsp;里是可以找到NODE.JS的~

克隆插件源码了嘛，看上面的截图，只要步骤对，都可以正常显示插件选项的。

**Comment by chiyu521** [comment]
总之&nbsp;感谢您的回复&nbsp;我再研究研究~

**Comment by chiyu521** [comment]
我重新GIT&nbsp;官方源码了 MENU里没有NODE&nbsp;要如何安装呢?

**Comment by maxlicheng** [comment]
你的路由器主控不支持node.js，官网自带有node.js的，不支持node.js的就不会显示。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: chiyu521 <notifications@github.com&gt;
发送时间: 2019年10月7日 12:09
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 老大请进 (#64)



我重新GIT&amp;nbsp;官方源码了 MENU里没有NODE&amp;nbsp;要如何安装呢?

**Comment by chiyu521** [comment]
支持的~用大屌源码没问题&nbsp;这是我第一次&nbsp;用官方源码&nbsp;就这样了~~

**Comment by maxlicheng** [comment]
> 支持的~用大屌源码没问题&nbsp;这是我第一次&nbsp;用官方源码&nbsp;就这样了~~

插件依赖于node，进入make menuconfig查看，Langages ---> Node.js --->查看Node.js选项中是否有可选项，如无说明你的路由器不支持Node.js。若L大的源码支持，而官方不支持，请尝试更新node源码。
- 1.在feeds.conf.default文件中添加如下语句
```
 src-git node https://github.com/nxhack/openwrt-node-packages.git
```
-  2.添加完成后，依次执行以下命令
```
./scripts/feeds update node
rm ./package/feeds/packages/node
rm ./package/feeds/packages/node-*
./scripts/feeds install -a -p node
```

**Comment by chiyu521** [comment]
不知道少了什么依赖支持&nbsp;虽然加了FEEDS&nbsp;也同步下来NODE了~&nbsp;但是&nbsp;依然MENU里没有NODE.JS选项~~&nbsp;我慢慢研究研究~
