### ISSUE TITLE
logcheck.sh 问题

### ISSUE THREAD

**Issue by 1715173329** [maxlicheng/luci-app-unblockmusic#65]
我在[新版本](https://github.com/project-openwrt/luci-app-unblockneteasemusic/commit/54cce44e58342cdcbc7a1158a25e0cf1b97321d3#diff-1c2f61096e793be2dd5eeaf1fb435015R138)中，使用计划任务代替后台运行，因此去掉了 `logcheck.sh` 中的[循环代码](https://github.com/project-openwrt/luci-app-unblockneteasemusic/commit/54cce44e58342cdcbc7a1158a25e0cf1b97321d3#diff-3783915447471cf0ecbdcc95e12e26c2L8)。
但我发现，在你现有的 [init脚本](https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/init.d/unblockmusic#L67) 中，仍然使用的是后台运行方式，并且[去掉了循环代码](https://github.com/maxlicheng/luci-app-unblockmusic/commit/8d9c1b19d33ffaa1d6ebd54b3311b48000dce86d#diff-185e4cdf56cbeb676447b110fc388e9aL6)。这样一来，你的 `logcheck.sh` 没有任何意义。

**Comment by maxlicheng** [comment]
谢谢，并不太懂这里面的逻辑，以为参考您的去掉会简洁一点，如果init改动太大，我还是改回去吧。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CN_SZTL <notifications@github.com&gt;
发送时间: 2019年10月6日 16:49
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65)




我在新版本中，使用计划任务代替后台运行，因此去掉了 logcheck.sh 中的循环代码。
但我发现，在你现有的 init脚本 中，仍然使用的是后台运行方式，并且去掉了循环代码。这样一来，你的 logcheck.sh 没有任何意义。

**Comment by 1715173329** [comment]
另外，通过检索，你虽然在 init 中写了[读取PORT变量](https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/root/etc/init.d/unblockmusic#L8)，但[luci](https://github.com/maxlicheng/luci-app-unblockmusic/blob/master/app/luasrc/model/cbi/unblockmusic.lua)中并未加入相关配置项，这表明PORT&HPORT并没有任何实际意义（空值）。
但在 71ecbc2 中，[引入了](https://github.com/maxlicheng/luci-app-unblockmusic/commit/71ecbc298448228117c183ac285d5fa68ed38cee#diff-b7c85bd5c73de263e4f6744e0111cfddR18)这两个空值，这样一来会导致无法启动。

**Comment by maxlicheng** [comment]
谢谢指点，自己也认为这是一个隐患，它的值是从config中的配置信息获取的，可能有些网友会交叉使用咱俩的版本，导致配置信息获取不了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CN_SZTL <notifications@github.com&gt;
发送时间: 2019年10月6日 16:57
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65)




另外，通过检索，你虽然在 init 中写了读取PORT变量，但luci中并未加入相关配置项，这表明PORT&amp;HPORT并没有任何实际意义（空值）。
 但在 71ecbc2 中，引入了这两个空值，这样一来会导致无法启动。

**Comment by 1715173329** [comment]
> 谢谢，并不太懂这里面的逻辑，以为参考您的去掉会简洁一点，如果init改动太大，我还是改回去吧。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CN_SZTL <notifications@github.com&gt; 发送时间: 2019年10月6日 16:49 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65) 我在新版本中，使用计划任务代替后台运行，因此去掉了 logcheck.sh 中的循环代码。 但我发现，在你现有的 init脚本 中，仍然使用的是后台运行方式，并且去掉了循环代码。这样一来，你的 logcheck.sh 没有任何意义。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

并不需要多大改动。。
但在当前情况下，推荐你恢复到之前的版本（

**Comment by maxlicheng** [comment]
对了，我看了获取远端新版本的逻辑，获取的是最新的提交，建议获取发行版会好点。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CN_SZTL <notifications@github.com&gt;
发送时间: 2019年10月6日 16:57
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65)




另外，通过检索，你虽然在 init 中写了读取PORT变量，但luci中并未加入相关配置项，这表明PORT&amp;HPORT并没有任何实际意义（空值）。
 但在 71ecbc2 中，引入了这两个空值，这样一来会导致无法启动。

**Comment by maxlicheng** [comment]
好，明白，在外面，需要晚点才能提交。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CN_SZTL <notifications@github.com&gt;
发送时间: 2019年10月6日 17:02
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65)



 
谢谢，并不太懂这里面的逻辑，以为参考您的去掉会简洁一点，如果init改动太大，我还是改回去吧。 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: CN_SZTL <notifications@github.com&gt; 发送时间: 2019年10月6日 16:49 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65) 我在新版本中，使用计划任务代替后台运行，因此去掉了 logcheck.sh 中的循环代码。 但我发现，在你现有的 init脚本 中，仍然使用的是后台运行方式，并且去掉了循环代码。这样一来，你的 logcheck.sh 没有任何意义。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
并不需要多大改动。。
 但在当前情况下，推荐你恢复到之前的版本（

**Comment by 1715173329** [comment]
> 谢谢指点，自己也认为这是一个隐患，它的值是从config中的配置信息获取的，可能有些网友会交叉使用咱俩的版本，导致配置信息获取不了。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CN_SZTL <notifications@github.com&gt; 发送时间: 2019年10月6日 16:57 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65) 另外，通过检索，你虽然在 init 中写了读取PORT变量，但luci中并未加入相关配置项，这表明PORT&amp;HPORT并没有任何实际意义（空值）。 但在 [71ecbc2](https://github.com/maxlicheng/luci-app-unblockmusic/commit/71ecbc298448228117c183ac285d5fa68ed38cee) 中，引入了这两个空值，这样一来会导致无法启动。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

在luci中保存配置之后，config应该会被覆写（不存在的配置项会不会被去掉暂不清楚）
但使用这样的变量确实存在隐患（

**Comment by 1715173329** [comment]
> 对了，我看了获取远端新版本的逻辑，获取的是最新的提交，建议获取发行版会好点。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CN_SZTL <notifications@github.com&gt; 发送时间: 2019年10月6日 16:57 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65) 另外，通过检索，你虽然在 init 中写了读取PORT变量，但luci中并未加入相关配置项，这表明PORT&amp;HPORT并没有任何实际意义（空值）。 但在 [71ecbc2](https://github.com/maxlicheng/luci-app-unblockmusic/commit/71ecbc298448228117c183ac285d5fa68ed38cee) 中，引入了这两个空值，这样一来会导致无法启动。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

发行版有时不会包含最新的错误修正，可能存在一定问题。。
有计划做成`stable / dev`两个选项，让用户自行选择。。

**Comment by 1715173329** [comment]
> 对了，我看了获取远端新版本的逻辑，获取的是最新的提交，建议获取发行版会好点。 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: CN_SZTL <notifications@github.com&gt; 发送时间: 2019年10月6日 16:57 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] logcheck.sh 问题 (#65) 另外，通过检索，你虽然在 init 中写了读取PORT变量，但luci中并未加入相关配置项，这表明PORT&amp;HPORT并没有任何实际意义（空值）。 但在 [71ecbc2](https://github.com/maxlicheng/luci-app-unblockmusic/commit/71ecbc298448228117c183ac285d5fa68ed38cee) 中，引入了这两个空值，这样一来会导致无法启动。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

个人觉得使用发行版并无太大意义，也并不存在稳定性一说。
将源项目硬写入系统中感觉过于蛋疼，在线下载升级还是非常有必要的（毕竟源项目为了fuck网易云音乐需要不断更新）。

附最新发行版版本号获取方式：
```bash
curl -s "https://github.com/nondanee/UnblockNeteaseMusic/releases" |grep -Eo 'releases\/tag\/v[0-9.]+' |sed -n 1p |sed 's#releases/tag/##g'
```
