### ISSUE TITLE
xargs: unrecognized option: i

### ISSUE THREAD

**Issue by xseven007** [maxlicheng/luci-app-unblockmusic#67]
默认编译的busybox不支持xargs -i，在运行的时候会导致无法生成ipset的表。

**Comment by maxlicheng** [comment]
是要增加相关的依赖嘛？



发自我的iPhone


------------------ Original ------------------

**Comment by xseven007** [comment]
不是，是openwrt默认编译配置生成的busybox是没有xargs -i的，所以换成原来的方式就可以了，如果是需要使用xargs，那么需要增加CONFIG_BUSYBOX_CONFIG_FEATURE_XARGS_SUPPORT_REPL_STR=y。应该是这一个，我正在编译加入这个条目。而且希望加入pac功能的开关，因为win10下的pac功能有一些问题，会导致一部分非网易云的网站也自己走代理。pacjsworker.exe问题目前还是有的，服务器重启可能会导致产生多个pacjsworker.exe进程。
