### ISSUE TITLE
能否实现openwrt iptables自动重定向

### ISSUE THREAD

**Issue by actg** [maxlicheng/luci-app-unblockmusic#7]
IOS上配置http代理某些其他网站工作异常，能否在openwrt上设置iptables自动代理？

**Comment by maxlicheng** [comment]
这属于路由器方面的问题了吧，没怎么研究过，留着看看有没有其他大神分享一下。

**Comment by actg** [comment]
参考这个https://www.right.com.cn/forum/thread-692049-1-1.html 1楼的实现ipset搭配iptables，完美实现自动代理，希望楼主给加到init.d脚本里面，完美解决

**Comment by maxlicheng** [comment]
> 参考这个https://www.right.com.cn/forum/thread-692049-1-1.html 1楼的实现ipset搭配iptables，完美实现自动代理，希望楼主给加到init.d脚本里面，完美解决

久等了，刚更新源码，新版本已支持iptables自动重定向，一键设置，自动代理。
