### ISSUE TITLE
求帮忙

### ISSUE THREAD

**Issue by gzsdbb** [maxlicheng/luci-app-unblockmusic#73]
在用koolshare的x64 2.33版本的固件
因为现在条件不允许不能自己译 所以求作者编译一下 谢谢

**Comment by maxlicheng** [comment]
> 在用koolshare的x64 2.33版本的固件
> 因为现在条件不允许不能自己译 所以求作者编译一下 谢谢

[x86.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.2)
