### ISSUE TITLE
Port must be a number higher than 0 and lower than 65535.

### ISSUE THREAD

**Issue by livse** [maxlicheng/luci-app-unblockmusic#75]
lede 自带的解锁服务，运行后 无法启动，log里面显示Port must be a number higher than 0 and lower than 65535.

**Comment by livse** [comment]
config里的配置
config unblockmusic
	option port '5200'
	option musicapptype 'kuwo'
	option enabled '1'

**Comment by maxlicheng** [comment]
哪个lede？你查看一下/etc/config/unblockmusic文件，里面的端口号参数是否存在，最好把文件内容粘贴上来。



发自我的iPhone


------------------ Original ------------------

**Comment by livse** [comment]
config unblockmusic
	option port '5200'
	option musicapptype 'kuwo'
	option enabled '1'


就这个

**Comment by livse** [comment]
koolshare版的lede

**Comment by maxlicheng** [comment]
> config unblockmusic
> option port '5200'
> option musicapptype 'kuwo'
> option enabled '1'
> 
> 就这个

正常内容应该是
```shell
config unblockmusic
	option enabled '0'
	option musicapptype 'kuwo'
	option port '5200'
	option hport '5201'
```

**Comment by maxlicheng** [comment]
> koolshare版的lede

更新一下新版本吧，自带的太久了。
[lede_x86.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/tag/v2.2.2)

**Comment by livse** [comment]
koolshare 版lede 更新不了

**Comment by maxlicheng** [comment]
> koolshare 版lede 更新不了

下载上面的安装包，手动更新

**Comment by livse** [comment]
3q 我去试试

**Comment by livse** [comment]
装不了。。。

**Comment by maxlicheng** [comment]
> config unblockmusic
> option port '5200'
> option musicapptype 'kuwo'
> option enabled '1'
> 
> 就这个

添加参数之后，正常了吗？

**Comment by maxlicheng** [comment]
> 装不了。。。

安装方法
将下载压缩包，解压，通过winscp将所有ipk上传到软路由tmp目录，用如下命令安装
注意安装顺序
```shell
opkg install libopenssl_1.0.2p-1_x86_64.ipk  
opkg install node_v8.16.1-1_x86_64.ipk
opkg install UnblockNeteaseMusic_0.20.0-1_x86_64.ipk
opkg install luci-app-unblockmusic_v2.2.2-10_all.ipk
```

**Comment by livse** [comment]
添加参数后正常了，万分感谢
