### ISSUE TITLE
使用issue13中提到的方法仍然没有node，但是lean的有

### ISSUE THREAD

**Issue by MiChuancey** [maxlicheng/luci-app-unblockmusic#76]
根据[issue](https://github.com/maxlicheng/luci-app-unblockmusic/issues/13)中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
menuconfig选中如下内容后，

arget System (MediaTek Ralink MIPS) --->
Subtarget (MT7621 based boards) --->
Target Profile (Xiaomi Router R3G) --->

language里的node里面仍是空的（换成X86会有选项）。

对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。

**Comment by libinanshu** [comment]
临时解决办法：把源码根目录config文件夹中Config-kernel.in 文件49行  default y if TARGET_pistachio 改为：default y

**Comment by maxlicheng** [comment]
> 根据[issue](https://github.com/maxlicheng/luci-app-unblockmusic/issues/13)中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
> menuconfig选中如下内容后，
> 
> arget System (MediaTek Ralink MIPS) --->
> Subtarget (MT7621 based boards) --->
> Target Profile (Xiaomi Router R3G) --->
> 
> language里的node里面仍是空的（换成X86会有选项）。
> 
> 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。

测试过，官方的是支持的，我用的[openwrt源码](https://github.com/openwrt/openwrt)，你把你的源码路径贴一下，我周末测试看看。

**Comment by MiChuancey** [comment]
https://git.openwrt.org/openwrt/openwrt.git



---原始邮件---
发件人: "maxlicheng"<notifications@github.com&gt;
发送时间: 2019年10月12日(星期六) 上午8:56
收件人: "maxlicheng/luci-app-unblockmusic"<luci-app-unblockmusic@noreply.github.com&gt;;
抄送: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)


 
根据issue中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
 menuconfig选中如下内容后，
 
arget System (MediaTek Ralink MIPS) ---&gt;
 Subtarget (MT7621 based boards) ---&gt;
 Target Profile (Xiaomi Router R3G) ---&gt;
 
language里的node里面仍是空的（换成X86会有选项）。
 
对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。
  
测试过，官方的是支持的，我用的openwrt源码，你把你的源码路径贴一下，我周末测试看看。

**Comment by maxlicheng** [comment]
> https://git.openwrt.org/openwrt/openwrt.git
> […](#)
> ---原始邮件--- 发件人: "maxlicheng"<notifications@github.com&gt; 发送时间: 2019年10月12日(星期六) 上午8:56 收件人: "maxlicheng/luci-app-unblockmusic"<luci-app-unblockmusic@noreply.github.com&gt;; 抄送: "Chuancey"<1210043347@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76) 根据issue中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码， menuconfig选中如下内容后， arget System (MediaTek Ralink MIPS) ---&gt; Subtarget (MT7621 based boards) ---&gt; Target Profile (Xiaomi Router R3G) ---&gt; language里的node里面仍是空的（换成X86会有选项）。 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。 测试过，官方的是支持的，我用的openwrt源码，你把你的源码路径贴一下，我周末测试看看。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

那咱们是同样的源码，我选择的是新三路由器，是支持的，你方便的话可以尝试选择新三路由器配置。如果不行你就得认真查查了。
我晚上下班回去才能验证小米的。

**Comment by maxlicheng** [comment]
> 根据[issue](https://github.com/maxlicheng/luci-app-unblockmusic/issues/13)中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
> menuconfig选中如下内容后，
> 
> arget System (MediaTek Ralink MIPS) --->
> Subtarget (MT7621 based boards) --->
> Target Profile (Xiaomi Router R3G) --->
> 
> language里的node里面仍是空的（换成X86会有选项）。
> 
> 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。

官方源码，make menuconfig选中路由器后，打开 .config文件，第240行，设置成y，完毕后保存，在进入make menuconfig即可找到本插件。
```shell
CONFIG_KERNEL_MIPS_FPU_EMULATOR=y
```
![opewrt-node](https://user-images.githubusercontent.com/40309661/66703200-98482480-ed42-11e9-991f-ca6fb2801909.jpg)

**Comment by MiChuancey** [comment]
设置FPU后luci里面仍然找不到插件，language里面的node也没有选项。
不知道你这个是选择的小米路由3G吗

> > 根据[issue](https://github.com/maxlicheng/luci-app-unblockmusic/issues/13)中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
> > menuconfig选中如下内容后，
> > arget System (MediaTek Ralink MIPS) --->
> > Subtarget (MT7621 based boards) --->
> > Target Profile (Xiaomi Router R3G) --->
> > language里的node里面仍是空的（换成X86会有选项）。
> > 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。
> 
> 官方源码，make menuconfig选中路由器后，打开 .config文件，第240行，设置成y，完毕后保存，在进入make menuconfig即可找到本插件。
> 
> ```shell
> CONFIG_KERNEL_MIPS_FPU_EMULATOR=y
> ```
> 
> ![opewrt-node](https://user-images.githubusercontent.com/40309661/66703200-98482480-ed42-11e9-991f-ca6fb2801909.jpg)

**Comment by maxlicheng** [comment]
主控一样的，只是路由器型号不一样。fpu跟主控有关系，跟路由器型号关系不大。在上班，晚上回去才能测试，你路由器可以选newifi-d2看看有没有，没有就说明小米有问题，一样没有说明还有选项没打开。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chuancey <notifications@github.com&gt;
发送时间: 2019年10月14日 14:59
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)




设置FPU后luci里面仍然找不到插件，language里面的node也没有选项。
 不知道你这个是选择的小米路由3G吗
   
根据issue中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
 menuconfig选中如下内容后，
 arget System (MediaTek Ralink MIPS) ---&gt;
 Subtarget (MT7621 based boards) ---&gt;
 Target Profile (Xiaomi Router R3G) ---&gt;
 language里的node里面仍是空的（换成X86会有选项）。
 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。
  
官方源码，make menuconfig选中路由器后，打开 .config文件，第240行，设置成y，完毕后保存，在进入make menuconfig即可找到本插件。
 CONFIG_KERNEL_MIPS_FPU_EMULATOR=y

**Comment by maxlicheng** [comment]
> 设置FPU后luci里面仍然找不到插件，language里面的node也没有选项。
> 不知道你这个是选择的小米路由3G吗
> 
> > > 根据[issue](https://github.com/maxlicheng/luci-app-unblockmusic/issues/13)中提到的方法，更新了node，我的路由器是小米路由3G，使用官方openwrt源码，
> > > menuconfig选中如下内容后，
> > > arget System (MediaTek Ralink MIPS) --->
> > > Subtarget (MT7621 based boards) --->
> > > Target Profile (Xiaomi Router R3G) --->
> > > language里的node里面仍是空的（换成X86会有选项）。
> > > 对lean的源码进行了相同的操作后，lean的language里的node会有一堆选项。
> > 
> > 
> > 官方源码，make menuconfig选中路由器后，打开 .config文件，第240行，设置成y，完毕后保存，在进入make menuconfig即可找到本插件。
> > ```shell
> > CONFIG_KERNEL_MIPS_FPU_EMULATOR=y
> > ```
> > 
> > 
> > ![opewrt-node](https://user-images.githubusercontent.com/40309661/66703200-98482480-ed42-11e9-991f-ca6fb2801909.jpg)

已验证，官方源码 小米3G有node.js，请自行排查一下。

**Comment by maxlicheng** [comment]
![1111](https://user-images.githubusercontent.com/40309661/66757477-db370300-eece-11e9-86a5-14bcbbf1b9cd.jpg)
![222](https://user-images.githubusercontent.com/40309661/66757478-dbcf9980-eece-11e9-9d30-51e160783e10.jpg)
![333](https://user-images.githubusercontent.com/40309661/66757481-dd995d00-eece-11e9-907a-857f9535f804.jpg)

**Comment by MiChuancey** [comment]
好奇怪，我的怎么没有

**Comment by MiChuancey** [comment]
能否说下你clone完openwrt源码、luci-源码，改fpu，还做了什么操作吗？

**Comment by maxlicheng** [comment]
> 能否说下你clone完openwrt源码、luci-源码，改fpu，还做了什么操作吗？

https://www.maxlicheng.com/openwrt/625.html

**Comment by MiChuancey** [comment]
感谢你的耐心解答。刚刚又重新clone了源码，发现可以了。编译好之后，安装貌似出现了问题，这样安装后luci界面有这个插件了。但没有运行。还请再帮忙看下，谢谢了

> root@OpenWrt:/tmp# opkg install node_v8.16.1-1_mipsel_24kc.ipk 
Installing node (v8.16.1-1) to root...
Configuring node.
root@OpenWrt:/tmp# opkg install UnblockNeteaseMusic_0.20.0-1_mipsel_24kc.ipk 
Installing UnblockNeteaseMusic (0.20.0-1) to root...
Configuring UnblockNeteaseMusic.
root@OpenWrt:/tmp# opkg install node_v8.16.1-1_mipsel_24kc.ipk 
Package node (v8.16.1-1) installed in root is up to date.
root@OpenWrt:/tmp# opkg install luci-app-unblockmusic_v2.2.2-10_all.ipk 
Installing luci-app-unblockmusic (v2.2.2-10) to root...
Configuring luci-app-unblockmusic.
uci: Entry not found
uci: Parse error (invalid command) at line 1, byte 0
ipset v6.38: The set with the given name does not exist

**Comment by MiChuancey** [comment]
![image](https://user-images.githubusercontent.com/37216768/66812817-31a35080-ef66-11e9-91bb-decb97e0a830.png)
![image](https://user-images.githubusercontent.com/37216768/66812863-44b62080-ef66-11e9-99f7-40537ffe08fe.png)

**Comment by maxlicheng** [comment]
ipset依赖没有装。。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chuancey <notifications@github.com&gt;
发送时间: 2019年10月15日 15:42
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)




感谢你的耐心解答。刚刚又重新clone了源码，发现可以了。编译好之后，安装貌似出现了问题，这样安装后luci界面有这个插件了。但没有运行。还请再帮忙看下，谢谢了
  
root@OpenWrt:/tmp# opkg install node_v8.16.1-1_mipsel_24kc.ipk
 Installing node (v8.16.1-1) to root...
 Configuring node.
 root@OpenWrt:/tmp# opkg install UnblockNeteaseMusic_0.20.0-1_mipsel_24kc.ipk
 Installing UnblockNeteaseMusic (0.20.0-1) to root...
 Configuring UnblockNeteaseMusic.
 root@OpenWrt:/tmp# opkg install node_v8.16.1-1_mipsel_24kc.ipk
 Package node (v8.16.1-1) installed in root is up to date.
 root@OpenWrt:/tmp# opkg install luci-app-unblockmusic_v2.2.2-10_all.ipk
 Installing luci-app-unblockmusic (v2.2.2-10) to root...
 Configuring luci-app-unblockmusic.
 uci: Entry not found
 uci: Parse error (invalid command) at line 1, byte 0
 ipset v6.38: The set with the given name does not exist

**Comment by MiChuancey** [comment]
![image](https://user-images.githubusercontent.com/37216768/66813217-f5bcbb00-ef66-11e9-8d65-acecf2e6a72d.png)

**Comment by maxlicheng** [comment]
libopenssl呢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chuancey <notifications@github.com&gt;
发送时间: 2019年10月15日 16:15
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)

**Comment by MiChuancey** [comment]
装了

**Comment by maxlicheng** [comment]
可以的试下重刷系统吧，也不知道缺依赖。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chuancey <notifications@github.com&gt;
发送时间: 2019年10月15日 16:24
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)




装了

**Comment by MiChuancey** [comment]
依赖应该是对的，不然装不上的

**Comment by maxlicheng** [comment]
缺少一些必要的库文件可以装上，但运行不了。x86的经常这样，你可以参考已经关闭的issues，koolshare lede相关issues。不过还是建议重刷试试。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Chuancey <notifications@github.com&gt;
发送时间: 2019年10月15日 16:39
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 使用issue13中提到的方法仍然没有node，但是lean的有 (#76)




依赖应该是对的，不然装不上的

**Comment by MiChuancey** [comment]
唉，刷了lean的固件。可以用了，，，，
