### ISSUE TITLE
新3用release里的v2.2.0-1编译的ipk无法运行

### ISSUE THREAD

**Issue by ShallCanyon** [maxlicheng/luci-app-unblockmusic#77]
newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci->Application里找不到luci-app-unblockmusic（尽管搜索可以搜到）
请问大佬是怎么编译新3的这个包的，node.js怎么处理

**Comment by maxlicheng** [comment]
更新node试试，https://www.maxlicheng.com/embedded/623.html



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ShallCanyon <notifications@github.com&gt;
发送时间: 2019年10月11日 23:47
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 新3用release里的v2.2.0-1编译的ipk无法运行 (#77)




newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci-&gt;Application里找不到luci-app-unblockmusic（尽管搜索可以搜到）
请问大佬是怎么编译新3的这个包的，node.js怎么处理

**Comment by maxlicheng** [comment]
> newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci->Application里找不到luci-app-unblockmusic（尽管搜索可以搜到）
> 请问大佬是怎么编译新3的这个包的，node.js怎么处理

请贴一下openwrt18.06.4源码路径，我抽空测试一下。

**Comment by ShallCanyon** [comment]
> 请贴一下openwrt18.06.4源码路径，我抽空测试一下。
openwrt官方的源码 https://github.com/openwrt/openwrt.git

**Comment by maxlicheng** [comment]
> newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci->Application里找不到luci-app-unblockmusic（尽管搜索可以搜到）
> 请问大佬是怎么编译新3的这个包的，node.js怎么处理

你正在运行路由器系统 可能少了个libopenssl 库，你自己编译安装这个库，然后再去安装2.2.0-1应该就可以运行了。

**Comment by ShallCanyon** [comment]
> 你正在运行路由器系统 可能少了个libopenssl 库，你自己编译安装这个库，然后再去安装2.2.0-1应该就可以运行了。

菜鸡技术不精，想问下大佬libopenssl库如何编译安装；谷歌过了似乎没找到答案，在menuconfig里有libopenssl但是在源码文件里找不到，make package/lib/openssl/compile也报错不能编译

另外node更新测试过了，也不行，在menuconfig的language->node里依然是空的

**Comment by hzdrro** [comment]
> 
> 
> > 你正在运行路由器系统 可能少了个libopenssl 库，你自己编译安装这个库，然后再去安装2.2.0-1应该就可以运行了。
> 
> 菜鸡技术不精，想问下大佬libopenssl库如何编译安装；谷歌过了似乎没找到答案，在menuconfig里有libopenssl但是在源码文件里找不到，make package/lib/openssl/compile也报错不能编译
> 
> 另外node更新测试过了，也不行，在menuconfig的language->node里依然是空的

Global build settings-Kernel build options-Compile the kernel with MIPS FPU Emulator勾选

**Comment by maxlicheng** [comment]
> > 你正在运行路由器系统 可能少了个libopenssl 库，你自己编译安装这个库，然后再去安装2.2.0-1应该就可以运行了。
> 
> 菜鸡技术不精，想问下大佬libopenssl库如何编译安装；谷歌过了似乎没找到答案，在menuconfig里有libopenssl但是在源码文件里找不到，make package/lib/openssl/compile也报错不能编译
> 
> 另外node更新测试过了，也不行，在menuconfig的language->node里依然是空的

官方源码，make menuconfig选中路由器后，打开 .config文件，第240行，设置成y，完毕后保存，在进入make menuconfig即可找到本插件。
```shell
CONFIG_KERNEL_MIPS_FPU_EMULATOR=y
```
![opewrt-node](https://user-images.githubusercontent.com/40309661/66703200-98482480-ed42-11e9-991f-ca6fb2801909.jpg)

**Comment by ShallCanyon** [comment]
确实按照楼上2位大佬的操作可以编译ipk了。源码更新了node，编译好2个ipk和libopenssl安装，但是依然启动失败，会不会我的路由器系统要刷 CONFIG_KERNEL_MIPS_FPU_EMULATOR=y 后的系统来安装才好？

**Comment by maxlicheng** [comment]
> 确实按照楼上2位大佬的操作可以编译ipk了。源码更新了node，编译好2个ipk和libopenssl安装，但是依然启动失败，会不会我的路由器系统要刷 CONFIG_KERNEL_MIPS_FPU_EMULATOR=y 后的系统来安装才好？

并不清楚你的系统缺少哪个依赖，建议自行排查。
node -v是否有node的版本号输出，
可尝试后台运行插件
```
node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
```

**Comment by ShallCanyon** [comment]
> 并不清楚你的系统缺少哪个依赖，建议自行排查。
> node -v是否有node的版本号输出，
> 可尝试后台运行插件
> 
> ```
> node /usr/share/UnblockNeteaseMusic/app.js -p 5200 &
> ```
运行两个node指令都出现
```
root@OpenWrt:~# node -v
Error loading shared library libcrypto.so.1.0.0: No such file or directory (needed by /usr/bin/node)
Error loading shared library libssl.so.1.0.0: No such file or directory (needed by /usr/bin/node)
```
以及一堆symbol not found:
```
Error relocating /usr/bin/node: EVP_get_digestbyname: symbol not found
```
libopenssl是确定安装了的，可以检测出来
```
root@OpenWrt:~# opkg files libopenssl
Package libopenssl1.1 (1.1.1d-1) is installed on root and has the following files:
/usr/lib/libcrypto.so.1.1
/usr/lib/libssl.so.1.1
```
是libopenssl的版本或者so库的位置不正确么？

**Comment by Dark-Existed** [comment]
> 更新node试试，https://www.maxlicheng.com/embedded/623.html 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ShallCanyon <notifications@github.com&gt; 发送时间: 2019年10月11日 23:47 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] 新3用release里的v2.2.0-1编译的ipk无法运行 (#77) newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci-&gt;Application里找不到luci-app-unblockmusic（尽管搜索可以搜到） 请问大佬是怎么编译新3的这个包的，node.js怎么处理 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好 我想问问 是不是不支持 MIPS_FPU 的 cpu 的路由器就无法使用
斐讯 k3 不支持 fpu 所以编译的时候是找不到的

**Comment by maxlicheng** [comment]
是的，readme里面已有注明，k3不支持node.js



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dark-Existed <notifications@github.com&gt;
发送时间: 2019年10月18日 10:08
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: maxlicheng <1661695769@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 新3用release里的v2.2.0-1编译的ipk无法运行 (#77)



 
更新node试试，https://www.maxlicheng.com/embedded/623.html 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: ShallCanyon <notifications@github.com&gt; 发送时间: 2019年10月11日 23:47 收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt; 抄送: Subscribed <subscribed@noreply.github.com&gt; 主题: 回复：[maxlicheng/luci-app-unblockmusic] 新3用release里的v2.2.0-1编译的ipk无法运行 (#77) newifi3-d2，openwrt18.06.4，用大佬的旧版本预编译ipk可以安装但是服务不能运行，想自己编译发现不支持node.js所以luci-&gt;Application里找不到luci-app-unblockmusic（尽管搜索可以搜到） 请问大佬是怎么编译新3的这个包的，node.js怎么处理 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
你好 我想问问 是不是不支持 MIPS_FPU 的 cpu 的路由器就无法使用
 斐讯 k3 不支持 fpu 所以编译的时候是找不到的
