### ISSUE TITLE
 lede安装报错，第一次安装

### ISSUE THREAD

**Issue by zengzhengrong** [maxlicheng/luci-app-unblockmusic#83]
```
root@Openwrt:~/x86# ls
UnblockNeteaseMusic_0.20.0-1_x86_64.ipk  luci-app-unblockmusic_v2.2.2-10_all.ipk
libopenssl_1.0.2p-1_x86_64.ipk           node_v8.16.1-1_x86_64.ipk
```
```
root@Openwrt:~/x86# opkg install libopenssl_1.0.2p-1_x86_64.ipk
Upgrading libopenssl on root from 1.0.2n-1 to 1.0.2p-1...
Configuring libopenssl.
```
```
root@Openwrt:~/x86# opkg install node_v8.16.1-1_x86_64.ipk
Installing node (v8.16.1-1) to root...
Configuring node.
```
```
root@Openwrt:~/x86# opkg install UnblockNeteaseMusic_0.20.0-1_x86_64.ipk
Installing UnblockNeteaseMusic (0.20.0-1) to root...
Configuring UnblockNeteaseMusic.
```
```
root@Openwrt:~/x86# opkg install luci-app-unblockmusic_v2.2.2-10_all.ipk
Installing luci-app-unblockmusic (v2.2.2-10) to root...
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-unblockmusic:
 *      bash *
 * opkg_install_cmd: Cannot install package luci-app-unblockmusic.
```

**Comment by maxlicheng** [comment]
> ```
> root@Openwrt:~/x86# ls
> UnblockNeteaseMusic_0.20.0-1_x86_64.ipk  luci-app-unblockmusic_v2.2.2-10_all.ipk
> libopenssl_1.0.2p-1_x86_64.ipk           node_v8.16.1-1_x86_64.ipk
> ```
> 
> ```
> root@Openwrt:~/x86# opkg install libopenssl_1.0.2p-1_x86_64.ipk
> Upgrading libopenssl on root from 1.0.2n-1 to 1.0.2p-1...
> Configuring libopenssl.
> ```
> 
> ```
> root@Openwrt:~/x86# opkg install node_v8.16.1-1_x86_64.ipk
> Installing node (v8.16.1-1) to root...
> Configuring node.
> ```
> 
> ```
> root@Openwrt:~/x86# opkg install UnblockNeteaseMusic_0.20.0-1_x86_64.ipk
> Installing UnblockNeteaseMusic (0.20.0-1) to root...
> Configuring UnblockNeteaseMusic.
> ```
> 
> ```
> root@Openwrt:~/x86# opkg install luci-app-unblockmusic_v2.2.2-10_all.ipk
> Installing luci-app-unblockmusic (v2.2.2-10) to root...
> Collected errors:
>  * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-unblockmusic:
>  *      bash *
>  * opkg_install_cmd: Cannot install package luci-app-unblockmusic.
> ```

缺少相关依赖，下载最新的[x86_64.zip](https://github.com/maxlicheng/luci-app-unblockmusic/releases/download/v2.2.3/x86_64.zip)，依次安装里面的ipk。
