### ISSUE TITLE
koolshare lede 2.32无法运行 感觉是libopenssl的问题？

### ISSUE THREAD

**Issue by Baronshaw** [maxlicheng/luci-app-unblockmusic#85]
最新版无法运行 
log:
Error relocating /usr/bin/node: SSL_CTX_set_next_proto_select_cb: symbol not found
Error relocating /usr/bin/node: SSL_CTX_set_next_protos_advertised_cb: symbol not found
Error relocating /usr/bin/node: SSL_get0_next_proto_negotiated: symbol not found
已经安装了x86_64里所有的依赖ipk.

**Comment by Baronshaw** [comment]
安装了libopenssl1.0.2p和更新了一堆软件包后可以了，不知道具体是哪个依赖的问题

**Comment by maxlicheng** [comment]
好，我抽空验证一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Baronshaw <notifications@github.com&gt;
发送时间: 2019年11月6日 15:52
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] koolshare lede 2.32无法运行 感觉是libopenssl的问题？ (#85)




安装了libopenssl1.0.2p和更新了一堆软件包后可以了，不知道具体是哪个依赖的问题

**Comment by Baronshaw** [comment]
验证了一下，和libopenssl1.0.2p无关，是node的依赖应用没有更新导致的
