### ISSUE TITLE
缺少bzip2依赖

### ISSUE THREAD

**Issue by lovezm** [maxlicheng/luci-app-unblockmusic#88]

**Comment by maxlicheng** [comment]
什么路由器呢，release里面的新三和x86.zip解压后，有个others-ipk文件夹，里面有所有的依赖。其他自编译的对照着others-ipk文件夹的名称找自己编译的ipk即可。

**Comment by lovezm** [comment]
新3啊 没有看到bzip2 - -

**Comment by maxlicheng** [comment]
> 新3啊 没有看到bzip2 - -

好，谢谢反馈，我抽空补一下。

**Comment by lovezm** [comment]
好的 感谢
