### ISSUE TITLE
koolshare2.33进程运行正常，客户端依然灰色

### ISSUE THREAD

**Issue by Zjp7518160** [maxlicheng/luci-app-unblockmusic#89]
安装luci-app-unblockmusic_v2.2.3-2_all.ipk后，进程运行正常，客户端依然灰色！使用旧版luci-app-unblockmusic_v2.2.2-10_all.ipk却能正常使用！

**Comment by outemancut** [comment]
因为2.2.3是大雕改的规则端口被指向了5202  所以安卓上面的不能自动解锁 2.2.2之前是没改的！

**Comment by leechaohua** [comment]
> 因为2.2.3是大雕改的规则端口被指向了5202 所以安卓上面的不能自动解锁 2.2.2之前是没改的！

哇靠，终于找到解决办法了，居然给人改了端口，都不通知作者啊，之前一直用5200

**Comment by maxlicheng** [comment]
> > 因为2.2.3是大雕改的规则端口被指向了5202 所以安卓上面的不能自动解锁 2.2.2之前是没改的！
> 
> 哇靠，终于找到解决办法了，居然给人改了端口，都不通知作者啊，之前一直用5200

嗯，我是知道的，只是最近太忙，没时间细化。之所以用5202，是因为L大优化后，电脑端异常，所以他补加了一个5202。
