### ISSUE TITLE
IOS按照说明设置歌曲还是灰体

### ISSUE THREAD

**Issue by whl1657343** [maxlicheng/luci-app-unblockmusic#9]
IOS按照说明设置歌曲还是灰体，请问是怎么回事？设置都是按照说明设置的。

**Comment by maxlicheng** [comment]
不太清楚是什么引起的，朋友反馈更新一下网易云客户端就可以了，我更新自己的客户端反而变灰了。
你可以用直接代理的方式进行歌曲下载，因为直接代理(全代理)所有流量都会走代理，所以下载完成后务必取消代理。
![Snipaste_2019-07-04_01-26-50](https://user-images.githubusercontent.com/40309661/60612413-1ec3a080-9dfb-11e9-8dae-4f1a3d7c523d.jpg)

**Comment by maxlicheng** [comment]
源项目中的issues有人也碰到类似的问题，可以过去参考一下：https://github.com/nondanee/UnblockNeteaseMusic/issues

**Comment by maxlicheng** [comment]
> IOS按照说明设置歌曲还是灰体，请问是怎么回事？设置都是按照说明设置的。

自己测试了一下，把IOS客户端降级为低版本就可以正常使用了，你抽空试试。
- [《IOS网易云音乐低版本客户端安装教程》](https://www.maxlicheng.com/github/590.html)
- [《【视频】低版本IOS网易云音乐客户端听周杰伦歌曲效果》](https://www.bilibili.com/video/av61511828/)
