### ISSUE TITLE
斐讯K3刷的OpenWRT可以用吗

### ISSUE THREAD

**Issue by JackPaVil** [maxlicheng/luci-app-unblockmusic#94]
LuCI openwrt-18.06 branch

**Comment by maxlicheng** [comment]
斐讯K3不支持哦，主控没有FPU。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: JackPaVil <notifications@github.com&gt;
发送时间: 2019年11月20日 10:44
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 斐讯K3刷的OpenWRT可以用吗 (#94)




LuCI openwrt-18.06 branch
