### ISSUE TITLE
橙子，帮忙把你B站里的俺的视频（OpenWrt的前生今世）下架吧，多谢！

### ISSUE THREAD

**Issue by esirplayground** [maxlicheng/luci-app-unblockmusic#97]
俺只把视频发布在youtube上，不想发布到天朝平台，望谅解

**Comment by maxlicheng** [comment]
好的，理解，我现在就撤下来。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: eSir <notifications@github.com&gt;
发送时间: 2019年11月25日 09:07
收件人: maxlicheng/luci-app-unblockmusic <luci-app-unblockmusic@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[maxlicheng/luci-app-unblockmusic] 橙子，帮忙把你B站里俺的视频下架吧，多谢！ (#97)




俺只把视频发布在youtube上，不想发布到天朝平台，望谅解

**Comment by esirplayground** [comment]
谢啦！^_^
